"""Pin the load-bearing rules of the pipelex-integrate skill template and its references."""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from scripts.gen_skill_docs import load_target_config, render_templates, resolve_output_dir


class TestPipelexIntegrateSkill:
    """The skill is executable guidance, so these tests guard the rules a user's
    codebase depends on: the write arm is the only arm, generated bytes are never
    touched, one directory per method, orphans are never deleted, sources are never
    mixed, a project-owned harness is kept, and the signature comes from the verdict.
    """

    REPO_ROOT = Path(__file__).parents[2]
    TEMPLATE = REPO_ROOT / "templates" / "skills" / "pipelex-integrate" / "SKILL.md.j2"
    REFERENCES_DIR = REPO_ROOT / "skills" / "pipelex-integrate" / "references"
    REFERENCES = ("typescript.md", "python.md", "codegen-check.mjs", "codegen_check.py")
    RULES = (
        "**The write arm, always.** Every `mthds_codegen` call passes `output_dir`.",
        "never by calling again without `output_dir` and writing the returned bytes yourself",
        "**Generated files are never opened for editing, never formatted, never linted.**",
        "**One directory per method.**",
        "You never delete an orphan either",
        "**Never generate from one source and run from another.**",
        "**A project that owns a codegen harness keeps it.** Never write a second generated layout",
        "**No `dropWireNulls` / `wireOutput` helper.**",
        "Do this **before** step 6",
        "**Check containment before the call rather than waiting for an error**",
        "never write the tree into the workshop's own directory and move it across afterwards",
        # The run route takes the bare pipe code; the verdict and the sidecar carry the namespaced ref.
        "**`pipe_ref` and the run's `pipe_code` are not the same string**",
        # A bundle is one closure: the call site submits every file, not just main.mthds.
        "It loads **every `.mthds` file of the committed bundle** at call time",
        # The containment reading is lexically wrong in both directions without resolving.
        "**Resolve both sides before comparing them**",
        "**Both inputs are known as soon as step 1 names the project, so do this reading there**",
        # A lock with no sidecar is also what this method's own interrupted run leaves.
        "**One lock-without-sidecar is this method's own, and relocating is the wrong answer for it**",
        # The harness keeps no sidecar by design, so step 4's rule cannot govern its layout.
        "**This is the one destination step 4's sidecar rule does not govern**",
        # A list output arrives as an array and a single-object parser rejects it.
        "**Narrow according to the output's `multiplicity`, which step 3 recorded**",
    )

    # The closed set of ways an instruction to end the run can be written. The continuing regions —
    # step 6's orphans branch, its failure-table row, refresh mode — are written without any of
    # them, and "do nothing else" is in the set because that is the phrase the decision struck, so
    # restoring it fails here instead of passing as a clarification of an unchanged rule.
    HALT_VOCABULARY = re.compile(r"\b(?:stop|stops|stopped|stopping|abort|aborts|aborting|halt|halts|do nothing else)\b", re.IGNORECASE)

    # How a region says the run proceeds past a write the check marks non-current. Used to FIND the
    # continuing regions rather than to spell them, so the condition assertions below reach whatever
    # those regions are later reworded into rather than only the wording in front of them now.
    CONTINUE_VOCABULARY = re.compile(
        r"carry on|carries on|continue to step|continues|runs on through|does not end (?:the run|a refresh)",
        re.IGNORECASE,
    )

    # The two halves of the ruled condition, each in the forms it may legitimately take: the branch
    # headers read "`orphans[]` non-empty and `drifts[]` empty", the refresh sentence reads "a
    # non-empty `orphans[]` with an empty `drifts[]`". Both halves must appear wherever the run
    # continues — dropping the `drifts[]` half is exactly what turns the branch back into the
    # blanket exemption that no gate could reach.
    ORPHANS_NON_EMPTY = re.compile(r"`orphans\[\]`[^.|]{0,40}non-empty|non-empty[^.|]{0,40}`orphans\[\]`", re.IGNORECASE)
    DRIFTS_EMPTY = re.compile(r"`drifts\[\]`[^.|]{0,40}(?<!non-)empty|(?<!non-)empty[^.|]{0,40}`drifts\[\]`", re.IGNORECASE)

    # The two halves searched for separately are not the condition, and a region can satisfy both
    # while stating neither as its condition: step 6's branch reads `drifts[]` three times, so
    # striking `and `drifts[]` empty` from its header leaves the later, non-conditional mentions to
    # answer `DRIFTS_EMPTY` — and the branch is the blanket exemption again with the suite green.
    # This pins the conjunction inside one clause, which is the only place it decides anything.
    CONDITION = re.compile(
        r"`orphans\[\]`[^.|]{0,30}non-empty[^.|]{0,30}`drifts\[\]`[^.|]{0,30}(?<!non-)empty"
        r"|non-empty[^.|]{0,30}`orphans\[\]`[^.|]{0,30}(?<!non-)empty[^.|]{0,30}`drifts\[\]`",
        re.IGNORECASE,
    )

    # `orphans[]` is always present and empty when clean; `drifts[]` is present only when non-empty
    # (`pipelex-mcp/SPEC.md` → `drifts?: unknown[]; // present when non-empty`). So the field the
    # continuing branch is read off is ABSENT in exactly the case that branch must recognise, and a
    # region telling an agent to read two lists owes it that the missing one is the empty one.
    ABSENT_DRIFTS_IS_EMPTY = re.compile(r"present only when (?:it is )?non-empty", re.IGNORECASE)

    # Continuing leaves the step-10 gate red, which is the consequence the report owes the user — but a
    # project that owns a codegen harness skips step 10 for its own check, so the claim is about the
    # step-10 gate only where one was installed. It was first written for the `python-pydantic`
    # consumer, who then got no gate at all; that consumer has one now, and the claim covers it.
    GATE_ONLY_WHERE_INSTALLED = re.compile(r"where the project has one|where a gate was installed", re.IGNORECASE)

    # The sentences that told a `python-pydantic` consumer it has no offline gate. `pipelex-sdk` 0.10.0
    # ships the check and step 10 installs it, so any of these coming back is a user told that nothing
    # can prove their generated tree current while the SDK they were just given carries the proof.
    STRUCK_NO_PYTHON_GATE = (
        "no gate is installed",
        "has no offline check yet",
        "which a `python-pydantic` consumer does not",
        "no offline drift check exists yet",
        "the only drift guard a Python consumer has",
        "the asymmetry sentence",
        "gets no offline gate yet",
    )

    # The sidecars both offline gates are run against, so the Python twin fails closed exactly where the
    # TypeScript script does. Bytes, because a byte-order mark and a non-UTF-8 file are cases; `None` is
    # no `sources.json` at all. Each non-object case reported `current` with exit 0 in some version of
    # one gate or the other before a guard went in.
    SIDECAR_CASES: tuple[tuple[bytes | None, int], ...] = (
        (b"null", 1),
        (b"[]", 1),
        (b'"a string"', 1),
        (b"42", 1),
        (b"true", 1),
        (b'{"method": {"id": "mt_x"}}', 0),
        (b'{"sources": {}}', 0),
        (b'{"sources": null}', 1),
        (b'{"sources": []}', 1),
        (b"{", 1),
        (b"\xef\xbb\xbf" + b'{"sources": {}}', 1),
        (b"\xff", 1),
        # Python's `json` accepts `NaN` where `JSON.parse` refuses it, so without its guard this one is
        # green in the Python gate and red in the TypeScript one.
        (b'{"sources": {}, "retries": NaN}', 1),
        # A sidecar recording sources has to say where the call site loads the bundle from, or a file added
        # there cannot be ruled out; and a `bundle_dir` is a non-empty string beside a `sources` object.
        (b'{"sources": {"methods/m/main.mthds": "0"}}', 1),
        (b'{"bundle_dir": "methods/m"}', 1),
        (b'{"sources": {}, "bundle_dir": null}', 1),
        (b'{"sources": {}, "bundle_dir": ""}', 1),
        (b'{"sources": {}, "bundle_dir": ["methods/m"]}', 1),
        (None, 0),
    )

    # The lowest `@pipelex/sdk` carrying everything the TypeScript output uses: the gate's three exports
    # arrived in 0.13.0, `method_id` runs in 0.14.0, `method_ref` runs in 0.16.0 (below it the option is typed
    # `never`, so a by-ref call site does not compile), and `prepareInputs` by all three sources — the upload the
    # call site's docstring points at — in 0.17.0, which also stopped it calling `/v1/build/inputs` and reading
    # a text field merely named `url` from disk. Step 8 raises an older pin to it, and every place that names a
    # TypeScript SDK version names this one.
    TYPESCRIPT_SDK_FLOOR = "0.17.0"
    VERSION = re.compile(r"\b\d+\.\d+(?:\.\d+)?\b")

    # A python-pydantic artifact body, stamped and locked by `stamped` and `write_python_project`.
    MODELS_BODY = "from pydantic import BaseModel\n\n\nclass Summary(BaseModel):\n    text: str\n"
    FINGERPRINT = "f" * 64

    # `is_current` is `false` on the continuing branch and on the stopping one alike, so a region
    # that continues has to say it is not what the branch is read from. This is the assertion the
    # first implementation lacked altogether, which is how a continue branch an agent could never
    # reach — it checks `is_current`, finds `false`, and stops — stayed green through a whole round.
    NOT_THE_VERDICT = re.compile(r"never (?:from )?`is_current`", re.IGNORECASE)

    # A mention of overwriting inside a continuing region is admissible only as a denial: the
    # hazardous case reports an EMPTY `orphans[]`, because every method of a target emits the same
    # file names, so the files that would be clobbered are overwritten without being reported at all.
    OVERWRITE_DENIAL = re.compile(r"\b(?:never|cannot|none|without)\b", re.IGNORECASE)

    @property
    def integrate(self) -> str:
        return self.TEMPLATE.read_text(encoding="utf-8")

    def render(self, target_name: str) -> str:
        """The skill as the named target renders it — what a user of that harness installs."""
        config = load_target_config(self.REPO_ROOT / "targets", target_name)
        rendered = render_templates(
            self.REPO_ROOT / "templates",
            self.REPO_ROOT,
            config.template_vars,
            include_skills=["pipelex-integrate"],
            target_name=config.name,
        )
        return next(content for path, content in rendered.items() if path.match("skills/pipelex-integrate/SKILL.md"))

    @staticmethod
    def the_line(body: str, needle: str) -> str:
        """The one line carrying `needle`. Two of them is a duplicated rule, which is its own defect."""
        lines = [line for line in body.splitlines() if needle in line]
        assert len(lines) == 1, f"expected exactly one line containing {needle!r}, found {len(lines)}"
        return lines[0]

    def test_the_rules_that_never_bend_are_stated(self) -> None:
        body = self.integrate
        for rule in self.RULES:
            assert rule in body, f"missing rule: {rule}"

    def test_signature_comes_from_the_verdict_and_the_heuristic_is_absent(self) -> None:
        body = self.integrate
        assert "A valid verdict carries **`main_pipe`**" in body
        assert "**`explicit: true`** — the one call in this plugin that wants the ceremonial" in body
        # The by-elimination output-concept heuristic was designed, then made obsolete before it shipped.
        assert "candidate output concepts" not in body
        assert "minus the input concepts minus natives" not in body
        # A by-ref / by-id source with no signature stops instead of guessing.
        assert "STOP and say the verdict carries no signature to type this integration exactly" in body
        # The entry pipe is the verdict's, which follows a package manifest; its absence has three causes, not one.
        assert "`main_pipe.pipe_ref` is the pipe a run with no pipe selector executes" in body
        assert "the method settles **no entry pipe**" in body
        assert "the workshop **predates the signature**" in body
        # The third cause was stated in step 3 but dropped from the failure table, whose remedy differs by cause.
        assert "the entry pipe's contract did not come back whole, which comes from the runner" in body
        # The same signature rides the text summary, so a host that drops structured content is not a dead end.
        assert "the **same fact on a second channel, not a fourth cause**" in body

    def test_the_wire_null_helper_is_never_installed(self) -> None:
        body = self.integrate
        assert "wire-output.ts" not in body
        assert "wireOutput(results" not in body
        for reference in self.REFERENCES:
            assert "dropWireNulls" not in (self.REFERENCES_DIR / reference).read_text(encoding="utf-8")

    def test_the_helper_budget_is_one_and_does_not_license_a_second(self) -> None:
        """The budget was two while the wire-output helper was the second. That helper was struck for
        being lossy and is forbidden outright below, so a surviving "at most two" is not merely a
        stale count — it is written permission to create the one thing the campaign removed, in a
        sentence that then says "and nothing else" about a list of one.
        """
        body = self.integrate
        assert "**Exactly one shared helper, created once per project" in body
        assert "one callable module per method plus one shared helper" in body
        assert "two shared helpers" not in body
        assert "at most two" not in body
        decisions = (self.REPO_ROOT / "docs" / "decisions.md").read_text(encoding="utf-8")
        assert "two shared helpers" not in decisions

    def test_failure_posture_pins_the_403_and_the_orphans(self) -> None:
        body = self.integrate
        assert "a **403** on `mthds_codegen` is a feature gate, not a key problem" in body
        assert 'never say "check your key" for a 403' in body
        assert '`kind: "paywall"`' in body
        assert "Report the orphan paths by name, never delete one" in body
        assert "never delete, move or clear the named file" in body
        assert "and never offer to" in body
        # A lock is not this method's without a sidecar naming it: same file names mean a silent overwrite, not an orphan.
        assert "is this method's only when a `sources.json` beside it names this method" in body
        assert "would silently overwrite the other method's stamped files rather than report an orphan" in body
        assert "report `drifts[]` verbatim and stop" in body
        # The emitter's extensionless import is a known defect: named, never patched in the stamped tree.
        assert 'a known defect of the ts-zod emitter, which writes `from "./types"`' in body
        assert "Changing the project's `moduleResolution` is the user's call to make, not yours" in body

    def continuing_regions(self, body: str) -> dict[str, str]:
        """Every region that tells the agent to proceed past a write the check marks non-current,
        keyed by where it is. Cut out by its anchor rather than searched for by the sentence under
        test, so the assertions apply to the region as a whole.
        """
        orphans = self.the_line(body, "- Success with **`orphans[]` non-empty")
        row = self.the_line(body, "| success with `orphans[]` non-empty")
        # Refresh mode's rule is one sentence run of a long paragraph, so cut it out rather than
        # scanning the paragraph — the rest of it is about content hashes and the call site.
        # The cut stops BEFORE "Any other `is_current: false` still ends the refresh": that sentence
        # is the stopping rule and belongs to the other branch, so including it would put a genuine
        # halt instruction inside a region the assertions below require not to halt — passing only
        # because `HALT_VOCABULARY` happens to spell "stop" and not "ends". That clause is asserted
        # on the whole paragraph instead, in the caller.
        opens = "**A non-empty `orphans[]` with an empty `drifts[]` does not end a refresh either**"
        closes = "`orphans_truncated: true` → say detection was partial."
        paragraph = self.the_line(body, opens)
        start = paragraph.index(opens)
        refresh = paragraph[start : paragraph.index(closes, start) + len(closes)]
        return {"step 6's orphans branch": orphans, "the failure table's orphans row": row, "refresh mode": refresh}

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_the_run_continues_on_orphans_alone_and_on_nothing_else(self, target_name: str) -> None:
        """Re-ruled by the founder on 2026-09-13 (`L-260912-3d5693`), replacing an earlier ruling of
        the same day that a review proved unimplementable. **The run continues when `orphans[]` is
        non-empty and `drifts[]` is empty, read off those two fields and never inferred from
        `is_current`; anything that also drifted ends the run.**

        What this test guards is the *condition*, because the condition is the whole decision and its
        absence is what made the first implementation green and wrong. `pipelex-mcp` sets
        `is_current: false` the moment a directory holds an orphan, so there is no
        success-with-orphans verdict to branch on: a branch phrased on the verdict is unreachable,
        and a branch phrased on nothing is a blanket exemption that swallows real drift. So every
        region that tells the agent to carry on must name both halves of the condition and must say
        the verdict is not what distinguishes them, and the stopping branch must claim every other
        false verdict. Asserting the continue wording exists — which is all the first test did —
        proves none of that.
        """
        body = self.render(target_name)
        regions = self.continuing_regions(body)

        for where, region in regions.items():
            assert self.CONTINUE_VOCABULARY.search(region), f"{target_name}: {where} no longer tells the agent to proceed"
            assert self.ORPHANS_NON_EMPTY.search(region), f"{target_name}: {where} continues without requiring a non-empty `orphans[]`"
            assert self.DRIFTS_EMPTY.search(region), (
                f"{target_name}: {where} continues without requiring an empty `drifts[]` — the ruled condition is gone "
                f"and the branch is the blanket exemption again: {region!r}"
            )
            assert self.CONDITION.search(region), (
                f"{target_name}: {where} names both halves somewhere but states neither as the condition it branches on, "
                f"which is the blanket exemption wearing the condition's vocabulary: {region!r}"
            )
            assert self.ABSENT_DRIFTS_IS_EMPTY.search(region), (
                f"{target_name}: {where} sends the agent to read `drifts[]` without saying it is present only when "
                f"non-empty, so the field the branch turns on is absent in exactly the case the branch is for: {region!r}"
            )
            assert self.NOT_THE_VERDICT.search(region), (
                f"{target_name}: {where} does not say the branch is read off the two lists and never from `is_current`, "
                f"which is `false` on both branches, so an agent reading the verdict takes the stopping one: {region!r}"
            )
            halt = self.HALT_VOCABULARY.search(region)
            assert halt is None, f"{target_name}: {where} ends the run ({halt.group(0)!r} in {region!r})"

        # The stopping branch claims every false verdict the condition above does not, so the two are
        # exhaustive: an agent holding a result with any non-orphan drift has exactly one branch.
        stops = self.the_line(body, "- Success with **`is_current: false` for any reason the branch above does not claim**")
        assert "a non-empty `drifts[]`, with or without orphans beside it" in stops
        assert self.HALT_VOCABULARY.search(stops), f"{target_name}: the non-orphan-drift branch no longer ends the run"
        stop_row = self.the_line(body, "| success with `is_current: false` for any other reason |")
        assert self.HALT_VOCABULARY.search(stop_row), f"{target_name}: the failure table's drift row no longer ends the run"
        assert "never commit a tree the check rejects" in stops

        # The success gate and the never-bend rule were right before the decision and the ruling
        # agrees with them: a clean tree is both fields, and two generations in one directory are
        # non-current by design. The gate also has to reach the branches that carry its two failures.
        gate = self.the_line(body, '- `status: "ok"`, `is_valid: true`, and `output_dir` present')
        assert "Confirm **`is_current: true`** and an empty **`orphans[]`**" in gate
        assert "the two branches below carry the two cases where it is not" in gate
        assert "two methods in one directory therefore read as permanently non-current, by design" in body

        # Refresh mode's own stopping rule, asserted on the whole paragraph because the continuing
        # region above is deliberately cut before it.
        assert "Any other `is_current: false` still ends the refresh, there as here." in body

        # Step 11 runs the gate this skill installed, and a run that continued past orphans reaches it
        # with that gate red BY DESIGN — which is new: before the ruling, such a run never got here.
        # Its two pre-existing dispositions do not cover the case, and the nearest of them reads as an
        # instruction to fix it, whose cheapest discharge is deleting the orphan the never-bend rules
        # forbid. So step 11 has to claim the case and say it is not the agent's to fix.
        verify = self.the_line(body, "then its type checker, then the gate you installed")
        assert "is neither, and it is not yours to fix" in verify, (
            f"{target_name}: step 11 does not claim the non-zero gate a continued run leaves behind, so its "
            f"'yours to fix' clause is the nearest reading: {verify!r}"
        )
        assert "Deleting an orphan to turn it green is the one remedy the rules that never bend forbid" in verify
        assert "dedicated directory per generation is the real one" in verify
        assert self.HALT_VOCABULARY.search(verify) is None, f"{target_name}: step 11 now ends the run over an orphan"

        # Step 4 enumerates the stops that leave a lock with no sidecar. Orphans alone is not one of
        # them any more, and the `is_current: false` item is qualified so the sentence stays true.
        assert "every stop between them — an `is_current: false` that step 6 does not let through, a partial write whose retry also failed —" in body

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_no_continuing_region_claims_an_overwrite_the_signal_cannot_show(self, target_name: str) -> None:
        """The first ruling made a loud report the whole protection against another method's
        same-named files having been overwritten by the write that just succeeded. Step 4 of this
        same skill says why that cannot be: every method of a target emits the same file names, so
        generating into a shared directory overwrites the other method's stamped files *rather than
        reporting an orphan*. A non-empty `orphans[]` therefore appears only where the prior tree
        held files this generation does not emit — which is exactly where nothing was clobbered.

        So a continuing region may mention overwriting only to rule it out, and what it owes instead
        is what the signal does mean: artifacts this generation does not list, none deleted, a
        dedicated directory per generation as the fix, and the gate red until the directory holds one
        generation. Step 12 is included because the run now provably reaches it and that is where
        the user reads any of this.
        """
        body = self.render(target_name)
        regions = dict(self.continuing_regions(body))
        regions["step 12's report"] = self.the_line(body, "What was generated and where; the target and why;")

        for where, region in regions.items():
            for found in re.finditer(r"overwr\w+", region):
                preceding = region[max(0, found.start() - 140) : found.start()]
                assert self.OVERWRITE_DENIAL.search(preceding), (
                    f"{target_name}: {where} states an overwrite as a possibility, which a non-empty `orphans[]` "
                    f"cannot show: {region[max(0, found.start() - 140) : found.end() + 80]!r}"
                )

        for where, region in regions.items():
            assert "this generation does not list" in region, f"{target_name}: {where} does not say what an orphan actually is"
            assert "dedicated directory per generation" in region, f"{target_name}: {where} drops the remedy"
        assert "none of them deleted" in regions["step 6's orphans branch"]
        assert "never delete one" in regions["the failure table's orphans row"]
        assert "never deletes them" in regions["refresh mode"]
        assert "none of them were deleted" in regions["step 12's report"]

        # Continuing leaves the gate this skill installs red, because that gate counts an orphan as a
        # drift — and the one way to turn it green is the deletion the never-bend rules forbid.
        assert "exits non-zero on this directory until it holds one generation" in regions["step 6's orphans branch"]
        assert "deleting an orphan to turn it green is the one remedy forbidden above" in regions["step 6's orphans branch"]
        assert "counts each as a drift until it holds one generation" in regions["the failure table's orphans row"]
        assert "the gate stays non-zero on that directory until it holds one generation" in regions["refresh mode"]
        assert "counts each one as a drift" in regions["step 12's report"]

        # Every region that makes the gate claim qualifies it, because a project that owns a codegen
        # harness skips step 10 and keeps its own check (see `GATE_ONLY_WHERE_INSTALLED`).
        # Keyed on the claim and not on the step number: refresh mode makes it as "the gate stays
        # non-zero" without naming step 10 at all, so a guard spelled `"step 10" in region` skips the
        # one region whose wording does not carry the number.
        for where, region in regions.items():
            if "gate" not in region:
                continue
            assert self.GATE_ONLY_WHERE_INSTALLED.search(region), (
                f"{target_name}: {where} claims the step-10 gate counts the orphans without saying the project may "
                f"have no step-10 gate — which a harness-owned project does not: {region!r}"
            )

        # And no region may carve the Python consumer out of the claim any more. Step 10 installs that
        # consumer's gate over `pipelex-sdk`'s own check, which counts an orphan as a drift exactly as the
        # TypeScript one does, so the red gate after a continued run is theirs too.
        for where, region in regions.items():
            for struck in self.STRUCK_NO_PYTHON_GATE:
                assert struck not in region, f"{target_name}: {where} still says a Python consumer has no gate: {struck!r}"

        # Partial detection stays partial detection rather than a clean tree.
        assert "say orphan detection was partial rather than reporting a clean tree" in regions["step 6's orphans branch"]
        for where in ("the failure table's orphans row", "refresh mode"):
            assert "`orphans_truncated: true` → say detection was partial" in regions[where]

        # The struck sentences of both superseded rulings, neither of which may come back.
        for struck in (
            "do nothing else",
            "the check owns the tree",
            "the check says the tree is current",
            "may therefore have been overwritten by the write that just succeeded",
            "this write may have overwritten same-named files of another method",
            "the regeneration has overwritten the other method's same-named files again",
        ):
            assert struck not in body, f"{target_name}: a struck phrase is back in the skill: {struck!r}"

    def test_the_call_sites_submit_the_whole_bundle_not_just_main(self) -> None:
        """Generation takes every `.mthds` file of the bundle, so the run must too.

        A call site that submits `main.mthds` alone type-checks, passes the offline gate, and then
        fails at load time on exactly the multi-file methods codegen handled correctly.
        """
        typescript = (self.REFERENCES_DIR / "typescript.md").read_text(encoding="utf-8")
        assert "mthds_contents: await readBundle()," in typescript
        # An interface has no implicit index signature, so it is not assignable to Record<string, unknown>.
        assert "export type SummarizePdfInputs = {" in typescript
        assert "export interface SummarizePdfInputs" not in typescript
        assert "**`SummarizePdfInputs` is a `type`, not an `interface`, and that is load-bearing.**" in typescript
        # A script merely named `codegen` is not evidence of a Pipelex harness.
        assert "read the script before believing it" in typescript
        assert 'name.endsWith(".mthds")' in typescript
        assert "mthds_contents: [bundle]" not in typescript
        # Its own relative imports need extensions on the resolution that meets the emitter defect.
        assert "**The three relative imports above are extensionless, which is correct only on a bundler resolution.**" in typescript

        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        assert "mthds_contents=_read_bundle()," in python
        assert 'sorted(BUNDLE_DIR.rglob("*.mthds"))' in python
        assert "BUNDLE_PATH" not in python

    def test_the_gate_fails_closed_on_a_malformed_sources_and_does_not_truncate(self) -> None:
        """The offline gate is the one executable artifact here, so two properties are pinned.

        A sidecar whose `sources` is present but not an object must fail the way an unreadable one
        does: coerced to `{}` it would check nothing, print nothing and exit 0 — the single input
        that is both silent and green. And the verdict's explanation must survive a pipe, which
        `process.exit` does not guarantee.
        """
        gate = (self.REFERENCES_DIR / "codegen-check.mjs").read_text(encoding="utf-8")
        # Neither `??` nor `?.` on the way to `sources`: both turn a hostile value into the
        # legitimate absent case. `?.` is the subtler of the two — a sidecar whose whole content is
        # `null`, `[]`, `"x"` or `42` is valid JSON and not an object, and `sidecar?.sources` makes
        # every one of them `undefined`, so the gate claims "a by-ref or by-id integration" and
        # exits 0 over a file that says nothing of the kind. Guard the sidecar, then its `sources`.
        assert "const sources = sidecar.sources;" in gate
        assert "const sources = sidecar?.sources" not in gate
        assert "?? {}" not in gate
        assert 'if (typeof sidecar !== "object" || sidecar === null || Array.isArray(sidecar)) {' in gate
        assert "not a JSON object, so staleness cannot be ruled out" in gate
        assert 'if (typeof sources !== "object" || sources === null || Array.isArray(sources)) {' in gate
        assert "is not an object, so staleness cannot be ruled out" in gate
        # No branch is both silent and green: absent and empty both announce themselves.
        assert "records no sources — a by-ref or by-id integration; source staleness does not apply" in gate
        assert "process.exitCode = await main(process.argv);" in gate
        # The default decoder strips a BOM, which would hash a BOM'd artifact as current.
        assert 'new TextDecoder("utf-8", { fatal: true, ignoreBOM: true })' in gate
        assert "process.exit(await main" not in gate

    @pytest.mark.parametrize(("sidecar", "expected_exit"), SIDECAR_CASES)
    def test_the_gate_runs_and_refuses_a_non_object_sidecar(self, sidecar: bytes | None, expected_exit: int, tmp_path: Path) -> None:
        """Run the gate, do not read it. Every case here was found by executing it, and the
        non-object-sidecar ones reported `current` with exit 0 before the guard went in — the
        failure the file's own header calls its one job to avoid.

        The lock check is made to yield no verdict (no `codegen.lock`), which the script reports on
        its own and which suppresses the sidecar check — so the cases are driven through a tree that
        reaches `checkSources`, i.e. one with a lock. Skipped when no `node` is on the PATH.
        """
        node = shutil.which("node")
        if node is None:
            pytest.skip("no node on the PATH")
        gate = tmp_path / "codegen-check.mjs"
        gate.write_bytes((self.REFERENCES_DIR / "codegen-check.mjs").read_bytes())
        # A lock the SDK cannot even be asked about would short-circuit the sidecar check, so stub
        # the one import and let the tree report itself current.
        stub = tmp_path / "node_modules" / "@pipelex" / "sdk"
        stub.mkdir(parents=True)
        (stub / "package.json").write_text(
            '{"name":"@pipelex/sdk","version":"0.0.0-stub","type":"module","main":"index.js","exports":{".":"./index.js"}}',
            encoding="utf-8",
        )
        (stub / "index.js").write_text(
            "export class CodegenLockError extends Error {}\n"
            "export const isStampableArtifactPath = (p) => p.endsWith('.ts') || p.endsWith('.py');\n"
            "export const runCodegenCheck = async () => ({ isCurrent: true, drifts: [], "
            "crateFingerprint: 'stubfingerprint', engineVersion: '0.0.0' });\n",
            encoding="utf-8",
        )
        tree = tmp_path / "generated" / "m"
        tree.mkdir(parents=True)
        (tree / "codegen.lock").write_text("lock_version = 1\n", encoding="utf-8")
        (tree / "types.ts").write_text("export const x = 1;\n", encoding="utf-8")
        if sidecar is not None:
            (tree / "sources.json").write_bytes(sidecar)
        result = subprocess.run(
            [node, str(gate), "generated/m"],
            cwd=tmp_path,
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == expected_exit, (
            f"sidecar {sidecar!r}: expected exit {expected_exit}, got {result.returncode}\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )
        if expected_exit == 0:
            assert "codegen-check: current" in result.stdout
        else:
            assert "codegen-check: drift" in result.stdout

    # A stub `@pipelex/sdk` whose check answers from the lock's text: a lock reading `crash` makes it throw
    # something that is not a `CodegenLockError`, `drift` makes it report a hand edit, anything else is current.
    STUB_SDK_THAT_CAN_CRASH = (
        "export class CodegenLockError extends Error {}\n"
        "export const isStampableArtifactPath = (p) => p.endsWith('.ts');\n"
        "export const runCodegenCheck = async ({ lockContent }) => {\n"
        "  if (lockContent.includes('crash')) throw new TypeError('the stub crashed');\n"
        "  if (lockContent.includes('drift')) return { isCurrent: false, crateFingerprint: 'stub', engineVersion: '0.0.0',\n"
        "    drifts: [{ category: 'hand-edited', path: 'types.ts', detail: 'edited below the stamp' }] };\n"
        "  return { isCurrent: true, drifts: [], crateFingerprint: 'stubfingerprint', engineVersion: '0.0.0' };\n"
        "};\n"
    )

    def run_typescript_gate(self, root: Path, *arguments: str, sdk_index: str | None) -> subprocess.CompletedProcess[str]:
        """Copy the shipped script into `root` and run it from there, beside a stub `@pipelex/sdk` whose module
        body is `sdk_index` — or with no `@pipelex/sdk` resolvable at all when it is `None`. Skipped when no
        `node` is on the PATH."""
        node = shutil.which("node")
        if node is None:
            pytest.skip("no node on the PATH")
        gate = root / "codegen-check.mjs"
        gate.write_bytes((self.REFERENCES_DIR / "codegen-check.mjs").read_bytes())
        if sdk_index is not None:
            stub = root / "node_modules" / "@pipelex" / "sdk"
            stub.mkdir(parents=True, exist_ok=True)
            (stub / "package.json").write_text(
                '{"name":"@pipelex/sdk","version":"0.0.0-stub","type":"module","main":"index.js","exports":{".":"./index.js"}}',
                encoding="utf-8",
            )
            (stub / "index.js").write_text(sdk_index, encoding="utf-8")
        return subprocess.run([node, str(gate), *arguments], cwd=root, capture_output=True, text=True, check=False)

    @staticmethod
    def write_typescript_tree(root: Path, name: str, lock: str) -> Path:
        tree = root / "generated" / name
        tree.mkdir(parents=True)
        (tree / "codegen.lock").write_text(f"{lock}\n", encoding="utf-8")
        (tree / "types.ts").write_text("export const x = 1;\n", encoding="utf-8")
        return tree

    @pytest.mark.parametrize(
        ("sdk_index", "expected_message"),
        [
            pytest.param(None, f"codegen-check: no verdict — @pipelex/sdk {TYPESCRIPT_SDK_FLOOR} or later is not importable (", id="not-installed"),
            pytest.param(
                "export class CodegenLockError extends Error {}\n",
                "the installed @pipelex/sdk has no isStampableArtifactPath, runCodegenCheck, so it predates the offline check. "
                f"Raise the project's @pipelex/sdk to {TYPESCRIPT_SDK_FLOOR} or later",
                id="too-old",
            ),
            pytest.param(
                'import "a-package-nobody-installed";\nexport const x = 1;\n',
                "codegen-check: no verdict — @pipelex/sdk could not be loaded (Error: Cannot find package 'a-package-nobody-installed'",
                id="broken-install",
            ),
        ],
    )
    def test_the_typescript_gate_has_no_verdict_when_the_sdk_cannot_be_used(
        self, sdk_index: str | None, expected_message: str, tmp_path: Path
    ) -> None:
        """A static import of `@pipelex/sdk` failed before the script ran, and the uncaught error exited 1,
        which a CI step reads as drift in a tree nobody checked — while the Python twin exits 2. Not
        installed, too old to carry the check, and installed but unloadable are all no verdict, and only the
        first is told it is not importable: a package the SDK itself imports going missing is the same
        `ERR_MODULE_NOT_FOUND`, and calling it a missing SDK would send the user after the wrong fix."""
        self.write_typescript_tree(tmp_path, "m", "lock_version = 1")
        result = self.run_typescript_gate(tmp_path, "generated/m", sdk_index=sdk_index)
        assert result.returncode == 2, self.explain(result)
        assert expected_message in result.stderr, self.explain(result)
        assert "node:internal" not in result.stderr, "the failure reached the user as a stack trace, not a verdict"
        if sdk_index is None:
            assert "npm run codegen:check" in result.stderr
        else:
            assert "is not importable" not in result.stderr
        assert result.stdout == ""

    def test_the_typescript_gate_has_no_verdict_when_a_check_throws(self, tmp_path: Path) -> None:
        """An error a check did not expect is no verdict for that directory — never an uncaught rejection that
        exits 1, reads as drift and leaves every later directory unchecked — and the precedence across
        directories still decides the exit code. The lock check is made to throw by the SDK, the source check
        by a sidecar nested deeper than sorting its entries can go, which `JSON.parse` accepts."""
        self.write_typescript_tree(tmp_path, "crash", "crash")
        self.write_typescript_tree(tmp_path, "drift", "drift")
        self.write_typescript_tree(tmp_path, "current", "current")
        deep = self.write_typescript_tree(tmp_path, "deep", "current")
        depth = 100_000
        (deep / "sources.json").write_text('{"sources": {"a": ' + "[" * depth + "]" * depth + ', "b": "x"}}', encoding="utf-8")

        crashed = self.run_typescript_gate(tmp_path, "generated/crash", sdk_index=self.STUB_SDK_THAT_CAN_CRASH)
        assert crashed.returncode == 2, self.explain(crashed)
        assert "  no verdict: the lock check failed — TypeError: the stub crashed" in crashed.stderr
        assert crashed.stdout.endswith("codegen-check: no verdict\n")

        overflowed = self.run_typescript_gate(tmp_path, "generated/deep", sdk_index=self.STUB_SDK_THAT_CAN_CRASH)
        assert overflowed.returncode == 2, self.explain(overflowed)
        assert "  no verdict: the source check failed — RangeError: " in overflowed.stderr
        assert overflowed.stdout.endswith("codegen-check: no verdict\n")

        # The run goes on past the crash to report every directory, and the worst verdict wins whatever the order.
        everything = self.run_typescript_gate(
            tmp_path, "generated/crash", "generated/drift", "generated/current", sdk_index=self.STUB_SDK_THAT_CAN_CRASH
        )
        assert everything.returncode == 2, self.explain(everything)
        assert "hand-edited: types.ts — edited below the stamp" in everything.stderr
        assert "generated/current\n  1 artifact(s) current" in everything.stdout
        reversed_order = self.run_typescript_gate(
            tmp_path, "generated/current", "generated/drift", "generated/crash", sdk_index=self.STUB_SDK_THAT_CAN_CRASH
        )
        assert reversed_order.returncode == 2, self.explain(reversed_order)
        no_crash = self.run_typescript_gate(tmp_path, "generated/drift", "generated/current", sdk_index=self.STUB_SDK_THAT_CAN_CRASH)
        assert no_crash.returncode == 1, self.explain(no_crash)

    def test_the_python_call_site_refuses_an_empty_bundle(self) -> None:
        """`Path.rglob` on a missing or empty directory returns nothing and raises nothing, so a
        wrong `BUNDLE_DIR` would submit `mthds_contents=[]` and fail server-side against the pipe
        instead of locally against the path. The TypeScript twin gets this free from `readdir`'s
        ENOENT; the Python one has to ask.
        """
        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        assert "if not contents:" in python
        assert 'raise FileNotFoundError(f"no .mthds files under {BUNDLE_DIR}")' in python

    def test_method_id_warns_and_refresh_leaves_the_call_site_alone(self) -> None:
        body = self.integrate
        assert "The catalog is unversioned" in body
        assert "proceed only on the user's say-so" in body
        assert "**The call site is edited only if it no longer type-checks or the `pipe` record no longer matches the signature**" in body
        assert '"generator": "pipelex-integrate"' in body

    def test_the_python_consumer_gets_a_gate_and_never_the_runtime(self) -> None:
        """`pipelex-sdk` 0.10.0 ships `run_codegen_check`, the pure-hashing mirror of `pipelex codegen
        check`, precisely so a hosted-API consumer has a gate without installing `pipelex`. Step 10 used
        to tell that consumer no gate existed; it now installs one shaped like the TypeScript branch.
        """
        body = self.integrate
        python_branch = self.the_line(body, "- **Python, `python-pydantic`**:")
        assert "copy [references/codegen_check.py](references/codegen_check.py) **verbatim** to `scripts/codegen_check.py`" in python_branch
        assert "**extend the project's existing aggregate gate**" in python_branch
        assert "**Run it with the project's own environment**" in python_branch
        assert "never add `pipelex` as a dependency to get a gate" in python_branch
        assert "exits `0` current / `1` drift or stale source / `2` no verdict" in python_branch
        assert "A project with no aggregate gate gets the script and one sentence in the report saying where to call it." in python_branch
        assert "an interpreter without the SDK, or a check that raises, exits `2` and says why" in python_branch
        # The failure row for a check that did not reach a verdict covers the Python gate's message too.
        raised = self.the_line(body, "exits `2` with `no verdict: the lock check failed` or `the source check failed` |")
        assert raised.startswith("| the TypeScript or the Python gate exits `2`"), raised
        assert "pipelex codegen check <dir>" in body
        # The gate runs the SDK's check, which the project's pin has to reach.
        assert "at least `pipelex-sdk` 0.10.0 for a `python-pydantic` consumer" in body
        assert "where the drift gate was wired and the command that runs it" in self.the_line(
            body, "What was generated and where; the target and why;"
        )

        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        assert "## The offline gate" in python
        assert "Copy `references/codegen_check.py` verbatim to `scripts/codegen_check.py`" in python
        assert "Run it from the project root with **the project's own environment**" in python
        assert "Do not add `pipelex` as a dependency to get a gate" in python
        assert "there is **no barrel** in `pipelex_sdk` by design" in python

        # Every place that told a Python consumer it has no gate, swept together: this skill, its
        # reference, the sibling skills that repeated the claim, and the repo's own account of itself.
        swept = (
            self.TEMPLATE,
            self.REFERENCES_DIR / "python.md",
            self.REPO_ROOT / "templates" / "skills" / "pipelex-edit" / "SKILL.md.j2",
            self.REPO_ROOT / "templates" / "skills" / "pipelex-design" / "SKILL.md.j2",
            self.REPO_ROOT / "docs" / "decisions.md",
            self.REPO_ROOT / "docs" / "build-targets.md",
            self.REPO_ROOT / "README.md",
            self.REPO_ROOT / "CHANGELOG.md",
        )
        for path in swept:
            text = path.read_text(encoding="utf-8")
            for struck in self.STRUCK_NO_PYTHON_GATE:
                assert struck not in text, f"{path.relative_to(self.REPO_ROOT)} still says a Python consumer has no gate: {struck!r}"

    def test_the_python_starter_harness_regenerates_without_the_runtime(self) -> None:
        """The Python starter's `make codegen` posts to the hosted `/v1/codegen` through `pipelex-sdk`,
        and a method directory may hold a `method.json` instead of a bundle. The skill used to branch
        its workshop fallback on a `pipelex` CLI being reachable, so on a starter-derived project it
        bypassed a generator that would have worked, and it had no path for a manifest at all.
        """
        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        _, harness = python.split("## A project that owns a codegen harness", 1)
        assert "needs `PIPELEX_API_KEY` from `.env` or the shell and no `pipelex` install" in harness
        assert "`make codegen-check`, the offline drift check, is the one target still shelling out to a `pipelex` CLI" in harness
        assert "a `method.json` holding exactly one of `method_id` / `method_ref`" in harness
        assert "write the `method.json` yourself, holding the selector and nothing else" in harness
        assert "Never generate a tree beside the manifest by hand." in harness
        assert "when `make codegen` stops because no `PIPELEX_API_KEY` reaches the project" in harness
        # The generated directory is the method directory's name with dashes turned into underscores, so
        # every generated path, output_dir and import in the section spells `<module>`, never `<name>`.
        assert "where `<module>` is `<name>` with its dashes turned into underscores" in harness
        assert "generated/<name>" not in harness and "generated.<name>" not in harness
        assert "with its entry file named `main.mthds`, which the starter's tests open" in harness
        for struck in ("both shelling out to a `pipelex` CLI", "when a `pipelex` CLI is reachable", "`PIPELEX=` points at an install"):
            assert struck not in python, f"python.md still branches on a pipelex CLI: {struck!r}"
        body = self.TEMPLATE.read_text(encoding="utf-8")
        assert "the Python starter's `make codegen` stops when no `PIPELEX_API_KEY` reaches the project" in body
        assert "`make codegen` shells out to a `pipelex` CLI" not in body

    @classmethod
    def stamped(cls, body: str) -> tuple[str, str]:
        """A Python artifact in the stamp grammar `pipelex-sdk` reads, and the body hash its lock records."""
        content_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()
        stamp = (
            "# >>> pipelex-codegen-stamp >>>\n"
            f"# crate_fingerprint: {cls.FINGERPRINT}\n"
            "# engine_version: 0.0.0\n"
            "# projection: types / python-pydantic\n"
            "# options: {}\n"
            f"# content_hash: {content_hash}\n"
            "# <<< pipelex-codegen-stamp <<<\n"
        )
        return stamp + body, content_hash

    def write_python_project(self, root: Path, method: str = "summarize") -> Path:
        """A bundle under `methods/<method>/` and its generated tree under `generated/<method>/` — stamped
        artifact, lock and sidecar, current by construction — and the tree's path."""
        bundle = root / "methods" / method / "main.mthds"
        bundle.parent.mkdir(parents=True)
        bundle.write_text(f'domain = "{method}"\n', encoding="utf-8")
        tree = root / "generated" / method
        tree.mkdir(parents=True)
        artifact, content_hash = self.stamped(self.MODELS_BODY)
        (tree / "models.py").write_text(artifact, encoding="utf-8")
        (tree / "codegen.lock").write_text(
            f'lock_version = 1\ncrate_fingerprint = "{self.FINGERPRINT}"\nengine_version = "0.0.0"\n\n'
            f'[[artifacts]]\npath = "models.py"\ncontent_hash = "{content_hash}"\n',
            encoding="utf-8",
        )
        source = f"methods/{method}/main.mthds"
        sidecar = {
            "generator": "pipelex-integrate",
            "method": {"files": [source]},
            "target": "python-pydantic",
            "bundle_dir": f"methods/{method}",
            "sources": {source: hashlib.sha256(bundle.read_bytes()).hexdigest()},
        }
        (tree / "sources.json").write_text(json.dumps(sidecar), encoding="utf-8")
        return tree

    @staticmethod
    def record_in_sidecar(tree: Path, **fields: object) -> None:
        """Set top-level fields of the tree's `sources.json`, removing each one given as `None`."""
        sidecar = json.loads((tree / "sources.json").read_text(encoding="utf-8"))
        for key, value in fields.items():
            if value is None:
                sidecar.pop(key, None)
            else:
                sidecar[key] = value
        (tree / "sources.json").write_text(json.dumps(sidecar), encoding="utf-8")

    def run_python_gate(self, root: Path, *arguments: str, without_site_packages: bool = False) -> subprocess.CompletedProcess[str]:
        """Copy the shipped script where step 10 puts it and run it from the project root, as a gate does.

        It runs under this suite's own interpreter, whose environment carries `pipelex-sdk` as a dev
        dependency; `without_site_packages` takes that environment away, as a wrong interpreter would.
        """
        gate = root / "scripts" / "codegen_check.py"
        gate.parent.mkdir(parents=True, exist_ok=True)
        gate.write_bytes((self.REFERENCES_DIR / "codegen_check.py").read_bytes())
        isolation = ["-I", "-S"] if without_site_packages else []
        return subprocess.run(
            [sys.executable, *isolation, str(gate), *arguments],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )

    @staticmethod
    def explain(result: subprocess.CompletedProcess[str]) -> str:
        return f"exit {result.returncode}\nstdout: {result.stdout}\nstderr: {result.stderr}"

    def test_the_python_gate_passes_a_current_tree(self, tmp_path: Path) -> None:
        """The baseline every other case mutates: a tree the SDK's check accepts, a sidecar whose source
        hash matches the bundle on disk, exit 0 and nothing on stderr."""
        self.write_python_project(tmp_path)
        result = self.run_python_gate(tmp_path, "generated/summarize")
        assert result.returncode == 0, self.explain(result)
        assert f"tree current (crate {self.FINGERPRINT[:12]}, engine 0.0.0)" in result.stdout
        assert result.stdout.endswith("codegen-check: current\n")
        assert result.stderr == ""

    @pytest.mark.parametrize(
        ("mutation", "expected_line"),
        [
            pytest.param("edit below the stamp", "hand-edited: models.py", id="hand-edited"),
            pytest.param("restamp a different body", "modified: models.py", id="modified"),
            pytest.param("delete the artifact", "missing: models.py", id="missing"),
            pytest.param("park a stamped file beside the tree", "orphan: stale.py", id="orphan"),
            pytest.param("give the artifact a byte-order mark", "hand-edited: models.py", id="bom-artifact"),
            pytest.param("edit the bundle", "stale-source: methods/summarize/main.mthds — edited since the types were generated", id="stale-source"),
            pytest.param(
                "delete the bundle", "stale-source: methods/summarize/main.mthds — recorded as a source but no longer on disk", id="source-gone"
            ),
        ],
    )
    def test_the_python_gate_reports_drift_and_stale_sources(self, mutation: str, expected_line: str, tmp_path: Path) -> None:
        """Exit 1 for every drift the SDK's check reports and for a bundle edited or removed since the
        types were generated. The orphan is the case the skill's continue path leaves behind: the gate
        counts it as a drift in Python exactly as in TypeScript."""
        tree = self.write_python_project(tmp_path)
        models = tree / "models.py"
        bundle = tmp_path / "methods" / "summarize" / "main.mthds"
        match mutation:
            case "edit below the stamp":
                models.write_text(models.read_text(encoding="utf-8") + "# a hand edit\n", encoding="utf-8")
            case "restamp a different body":
                models.write_text(self.stamped(self.MODELS_BODY + "# a second generation\n")[0], encoding="utf-8")
            case "delete the artifact":
                models.unlink()
            case "park a stamped file beside the tree":
                (tree / "stale.py").write_text(self.stamped("VALUE = 1\n")[0], encoding="utf-8")
            case "give the artifact a byte-order mark":
                models.write_bytes(b"\xef\xbb\xbf" + models.read_bytes())
            case "edit the bundle":
                bundle.write_text(bundle.read_text(encoding="utf-8") + "# edited\n", encoding="utf-8")
            case "delete the bundle":
                bundle.unlink()
            case _:
                pytest.fail(f"unknown mutation {mutation!r}")
        result = self.run_python_gate(tmp_path, "generated/summarize")
        assert result.returncode == 1, self.explain(result)
        assert expected_line in result.stderr, self.explain(result)
        assert "Run /pipelex-integrate to refresh the generated types." in result.stderr
        assert result.stdout.endswith("codegen-check: drift\n")

    @pytest.mark.parametrize(
        ("change", "expected_lines"),
        [
            pytest.param(
                "add a file beside the recorded one",
                ("stale-source: methods/summarize/extra.mthds — added to the bundle since the types were generated",),
                id="added-beside",
            ),
            pytest.param(
                "add a file two directories down",
                ("stale-source: methods/summarize/nested/deeper/extra.mthds — added to the bundle since the types were generated",),
                id="added-nested",
            ),
            pytest.param(
                "drop the bundle directory from the sidecar",
                ("stale-source: sources.json — records sources but no `bundle_dir`, so a .mthds file added to the bundle cannot be ruled out",),
                id="no-bundle-dir",
            ),
            pytest.param(
                "narrow the recorded bundle directory",
                (
                    "stale-source: methods/summarize/main.mthds — recorded as a source but not under methods/summarize/nested, "
                    "so the call site does not load it",
                    "stale-source: methods/summarize/nested/other.mthds — added to the bundle since the types were generated",
                ),
                id="source-outside-bundle",
            ),
            pytest.param(
                "empty the bundle directory",
                (
                    "stale-source: methods/summarize — holds no .mthds file, so the call site has no bundle to load",
                    "stale-source: methods/summarize/main.mthds — recorded as a source but no longer on disk",
                ),
                id="bundle-empty",
            ),
            pytest.param(
                "remove the bundle directory",
                (
                    "stale-source: methods/summarize — recorded as the bundle directory but no longer on disk",
                    "stale-source: methods/summarize/main.mthds — recorded as a source but no longer on disk",
                ),
                id="bundle-gone",
            ),
            pytest.param(
                "replace the bundle directory with a file",
                ("stale-source: methods/summarize — recorded as the bundle directory but not a directory",),
                id="bundle-not-a-directory",
            ),
            pytest.param("record a nested file with the main one", (), id="current-nested"),
            pytest.param("add a file that is not a .mthds file", (), id="current-other-file"),
        ],
    )
    def test_both_gates_catch_a_file_added_to_the_bundle(self, change: str, expected_lines: tuple[str, ...], tmp_path: Path) -> None:
        """The call site loads every `.mthds` file under its bundle directory, so a file added there changes what
        runs while every recorded hash still matches, and both gates once stayed green over it: they hashed the
        files `sources.json` recorded and nothing else. They now list the sidecar's `bundle_dir` the way their
        language's call site lists it, and both report each change with the same lines, on one project."""
        python_script = (self.REFERENCES_DIR / "codegen_check.py").read_text(encoding="utf-8")
        typescript_script = (self.REFERENCES_DIR / "codegen-check.mjs").read_text(encoding="utf-8")
        assert 'root.rglob("*.mthds")' in python_script, "the Python gate no longer lists the bundle as the Python call site does"
        assert "readdir(root, { recursive: true })" in typescript_script, "the TypeScript gate no longer lists the bundle as its call site does"
        assert '.filter((entry) => entry.endsWith(".mthds"))' in typescript_script

        tree = self.write_python_project(tmp_path)
        bundle = tmp_path / "methods" / "summarize"
        match change:
            case "add a file beside the recorded one":
                (bundle / "extra.mthds").write_text('domain = "extra"\n', encoding="utf-8")
            case "add a file two directories down":
                (bundle / "nested" / "deeper").mkdir(parents=True)
                (bundle / "nested" / "deeper" / "extra.mthds").write_text('domain = "extra"\n', encoding="utf-8")
            case "drop the bundle directory from the sidecar":
                self.record_in_sidecar(tree, bundle_dir=None)
            case "narrow the recorded bundle directory":
                (bundle / "nested").mkdir()
                (bundle / "nested" / "other.mthds").write_text('domain = "other"\n', encoding="utf-8")
                self.record_in_sidecar(tree, bundle_dir="methods/summarize/nested")
            case "empty the bundle directory":
                (bundle / "main.mthds").unlink()
            case "remove the bundle directory":
                shutil.rmtree(bundle)
            case "replace the bundle directory with a file":
                shutil.rmtree(bundle)
                bundle.write_text("not a directory\n", encoding="utf-8")
            case "record a nested file with the main one":
                nested = bundle / "nested" / "helpers.mthds"
                nested.parent.mkdir()
                nested.write_text('domain = "helpers"\n', encoding="utf-8")
                sidecar = json.loads((tree / "sources.json").read_text(encoding="utf-8"))
                sources = {**sidecar["sources"], "methods/summarize/nested/helpers.mthds": hashlib.sha256(nested.read_bytes()).hexdigest()}
                self.record_in_sidecar(tree, sources=sources)
            case "add a file that is not a .mthds file":
                (bundle / "README.md").write_text("# summarize\n", encoding="utf-8")
            case _:
                pytest.fail(f"unknown change {change!r}")

        python = self.run_python_gate(tmp_path, "generated/summarize")
        typescript = self.run_typescript_gate(tmp_path, "generated/summarize", sdk_index=self.STUB_SDK_THAT_CAN_CRASH)
        for name, result in (("python", python), ("typescript", typescript)):
            reported = [line.strip() for line in result.stderr.splitlines() if line.strip().startswith("stale-source: ")]
            if not expected_lines:
                assert result.returncode == 0, f"{name}: {self.explain(result)}"
                assert reported == [], f"{name}: {self.explain(result)}"
                continue
            assert result.returncode == 1, f"{name}: {self.explain(result)}"
            for expected in expected_lines:
                assert expected in reported, f"{name} did not report {expected!r}\n{self.explain(result)}"
            assert result.stdout.endswith("codegen-check: drift\n"), f"{name}: {self.explain(result)}"
        # Twins: the same paths reported in the same order. Only an OS error's own wording may differ between them.
        python_paths = [line.strip().split(" — ")[0] for line in python.stderr.splitlines() if line.strip().startswith("stale-source: ")]
        typescript_paths = [line.strip().split(" — ")[0] for line in typescript.stderr.splitlines() if line.strip().startswith("stale-source: ")]
        assert python_paths == typescript_paths, f"python: {python.stderr}\ntypescript: {typescript.stderr}"

    def test_the_sidecar_records_the_bundle_directory_and_every_reader_uses_it(self) -> None:
        """The gates can list the bundle only because step 7 records its directory, and the gates are not the only
        readers the fix had to reach. Refresh mode took its file set from `method.files`, so it regenerated from the
        old set while the call site ran the new one; the editing skills matched a sidecar only on the files its
        `sources` named, which a new file never is; and a standalone organize, which rewrites the bundle's files
        wholesale, said nothing at all."""
        body = self.integrate
        assert '"bundle_dir": "methods/summarize-pdf",' in body
        assert "**`bundle_dir` is the directory step 9's call site loads the bundle from**" in body
        # The sidecar example and the TypeScript call site name the same directory.
        typescript = (self.REFERENCES_DIR / "typescript.md").read_text(encoding="utf-8")
        assert 'const BUNDLE_DIR = path.join(process.cwd(), "methods", "summarize-pdf");' in typescript
        assert "from the directory step 7 records as `bundle_dir` and from no other" in body
        assert "**file set, which is re-read from `bundle_dir` and never taken from `method.files`**" in self.refresh_cells(body)["taken from disk"]
        assert "a file edited, removed or added" in self.refresh_cells(body)["re-checked"]
        assert "never add the file's hash to `sources` by hand" in body

        templates = self.REPO_ROOT / "templates" / "skills"
        edit = (templates / "pipelex-edit" / "SKILL.md.j2").read_text(encoding="utf-8")
        assert "**or whose `bundle_dir` holds a `.mthds` file this edit created**" in edit
        design = (templates / "pipelex-design" / "SKILL.md.j2").read_text(encoding="utf-8")
        assert "**or whose `bundle_dir` holds a `.mthds` file this re-entry created**" in design
        organize = (templates / "pipelex-organize" / "SKILL.md.j2").read_text(encoding="utf-8")
        assert "**When invoked on its own rather than by `/pipelex-design`**" in organize
        assert "or whose `bundle_dir` is this directory or holds it" in organize

    @pytest.mark.parametrize(
        "mutation",
        [
            "delete the lock",
            "corrupt the lock",
            "name a symlink to the tree",
            "name a directory that does not exist",
            "delete the lock, break the sidecar",
        ],
    )
    def test_the_python_gate_has_no_verdict_without_a_readable_lock(self, mutation: str, tmp_path: Path) -> None:
        """Exit 2, never 1: no lock, a malformed lock and a symlinked generated directory are the absence
        of a verdict, and a tree with no verdict is not read on to its sidecar — so a broken sidecar
        beside a missing lock still reports no verdict rather than drift."""
        tree = self.write_python_project(tmp_path)
        argument = "generated/summarize"
        match mutation:
            case "delete the lock":
                (tree / "codegen.lock").unlink()
            case "corrupt the lock":
                (tree / "codegen.lock").write_text("lock_version = [\n", encoding="utf-8")
            case "name a symlink to the tree":
                (tmp_path / "generated" / "link").symlink_to(tree, target_is_directory=True)
                argument = "generated/link"
            case "name a directory that does not exist":
                argument = "generated/nowhere"
            case "delete the lock, break the sidecar":
                (tree / "codegen.lock").unlink()
                (tree / "sources.json").write_bytes(b"null")
            case _:
                pytest.fail(f"unknown mutation {mutation!r}")
        result = self.run_python_gate(tmp_path, argument)
        assert result.returncode == 2, self.explain(result)
        assert "  no verdict: " in result.stderr
        assert "stale-source" not in result.stderr
        assert result.stdout.endswith("codegen-check: no verdict\n")

    @pytest.mark.parametrize(("sidecar", "expected_exit"), SIDECAR_CASES)
    def test_the_python_gate_refuses_every_sidecar_the_typescript_gate_refuses(
        self, sidecar: bytes | None, expected_exit: int, tmp_path: Path
    ) -> None:
        """The same table as the TypeScript gate's run, over a real current tree: the two scripts must
        fail closed on the same malformed sidecars and stay green on the same legitimate ones."""
        tree = self.write_python_project(tmp_path)
        if sidecar is None:
            (tree / "sources.json").unlink()
        else:
            (tree / "sources.json").write_bytes(sidecar)
        result = self.run_python_gate(tmp_path, "generated/summarize")
        assert result.returncode == expected_exit, f"sidecar {sidecar!r}: {self.explain(result)}"
        if expected_exit == 0:
            assert result.stdout.endswith("codegen-check: current\n")
        else:
            assert "stale-source: sources.json" in result.stderr
            assert result.stdout.endswith("codegen-check: drift\n")

    def test_the_python_gate_reports_the_worst_verdict_across_directories(self, tmp_path: Path) -> None:
        """Precedence is no verdict > drift > current, whatever order the directories are named in, and a
        gate given no directory has nothing to check."""
        self.write_python_project(tmp_path, "summarize")
        drifted = self.write_python_project(tmp_path, "extract")
        (drifted / "models.py").write_text((drifted / "models.py").read_text(encoding="utf-8") + "# a hand edit\n", encoding="utf-8")
        unlocked = self.write_python_project(tmp_path, "classify")
        (unlocked / "codegen.lock").unlink()

        assert self.run_python_gate(tmp_path, "generated/summarize").returncode == 0
        assert self.run_python_gate(tmp_path, "generated/extract", "generated/summarize").returncode == 1
        assert self.run_python_gate(tmp_path, "generated/classify", "generated/extract", "generated/summarize").returncode == 2
        assert self.run_python_gate(tmp_path, "generated/summarize", "generated/extract", "generated/classify").returncode == 2

        usage = self.run_python_gate(tmp_path)
        assert usage.returncode == 2
        assert usage.stderr.startswith("usage: python scripts/codegen_check.py")

    def test_the_python_gate_has_no_verdict_outside_the_projects_environment(self, tmp_path: Path) -> None:
        """Run by an interpreter that cannot import `pipelex-sdk` — a system `python3` instead of the
        project's environment — the gate exits 2 and says how to run it. An uncaught ImportError would
        exit 1, which a CI step reads as drift in a tree nobody checked."""
        self.write_python_project(tmp_path)
        result = self.run_python_gate(tmp_path, "generated/summarize", without_site_packages=True)
        assert result.returncode == 2, self.explain(result)
        assert "pipelex-sdk 0.10.0 or later is not importable" in result.stderr
        assert "uv run python scripts/codegen_check.py" in result.stderr

    @pytest.mark.parametrize(
        ("stub_files", "expected_error"),
        [
            pytest.param(
                {"codegen_check.py": 'raise TypeError("the stub crashed at import")\n'},
                "TypeError: the stub crashed at import",
                id="raises-at-import",
            ),
            pytest.param(
                {"codegen_check.py": "def run_codegen_check(*, root):\n    return None\n", "errors.py": "class CodegenLockError(Exception\n"},
                "SyntaxError: ",
                id="corrupt-file",
            ),
        ],
    )
    def test_the_python_gate_has_no_verdict_when_the_sdk_fails_while_loading(
        self, stub_files: dict[str, str], expected_error: str, tmp_path: Path
    ) -> None:
        """An installed `pipelex-sdk` that raises something other than `ImportError` while it loads — a pydantic
        whose pydantic-core does not match it raises `SystemError`, a corrupt SDK file `SyntaxError` — escaped the
        import guard, printed a traceback and exited 1, which every gate reads as drift. It is no verdict, named
        for what it is: a broken environment to reinstall, not an interpreter to change."""
        self.write_python_project(tmp_path)
        stub = tmp_path / "stub-site" / "pipelex_sdk"
        stub.mkdir(parents=True)
        (stub / "__init__.py").write_text("", encoding="utf-8")
        for name, body in stub_files.items():
            (stub / name).write_text(body, encoding="utf-8")
        gate = tmp_path / "scripts" / "codegen_check.py"
        gate.parent.mkdir(parents=True)
        gate.write_bytes((self.REFERENCES_DIR / "codegen_check.py").read_bytes())
        # The stub comes first on the path, so it shadows the real `pipelex-sdk` this suite's environment carries.
        environment = {**os.environ, "PYTHONPATH": str(stub.parent), "PYTHONDONTWRITEBYTECODE": "1"}
        result = subprocess.run(
            [sys.executable, str(gate), "generated/summarize"],
            cwd=tmp_path,
            env=environment,
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 2, self.explain(result)
        loading = "codegen-check: no verdict — pipelex-sdk failed while loading ("
        assert f"{loading}{expected_error}" in result.stderr, self.explain(result)
        assert "reinstall its dependencies" in result.stderr
        assert "is not importable" not in result.stderr
        assert "Traceback" not in result.stderr
        assert result.stdout == ""

    def test_the_python_gate_has_no_verdict_when_the_lock_check_raises(self, tmp_path: Path) -> None:
        """Whatever the lock check raises beyond the states it turns into outcomes is no verdict for that
        directory, and the run goes on to check the rest. A lock holding an integer longer than Python's
        integer-string limit is the clean trigger: `tomllib` raises a `ValueError` the SDK does not wrap,
        and before the guard it ended the whole run with exit 1 — drift — leaving later directories unread."""
        huge = self.write_python_project(tmp_path, "huge")
        (huge / "codegen.lock").write_text("lock_version = " + "9" * 5000 + "\n", encoding="utf-8")
        drifted = self.write_python_project(tmp_path, "drift")
        (drifted / "models.py").write_text((drifted / "models.py").read_text(encoding="utf-8") + "# a hand edit\n", encoding="utf-8")
        self.write_python_project(tmp_path, "current")

        alone = self.run_python_gate(tmp_path, "generated/huge")
        assert alone.returncode == 2, self.explain(alone)
        assert "  no verdict: the lock check failed — ValueError: Exceeds the limit" in alone.stderr
        assert "Traceback" not in alone.stderr
        assert alone.stdout.endswith("codegen-check: no verdict\n")

        # The directories after the one that raised are still checked, and the worst verdict wins.
        everything = self.run_python_gate(tmp_path, "generated/huge", "generated/drift", "generated/current")
        assert everything.returncode == 2, self.explain(everything)
        assert "hand-edited: models.py" in everything.stderr
        assert "generated/current\n  tree current (crate" in everything.stdout
        assert self.run_python_gate(tmp_path, "generated/drift", "generated/current").returncode == 1

    def test_the_python_gate_has_no_verdict_behind_a_directory_it_cannot_search(self, tmp_path: Path) -> None:
        """A lock behind a directory the process cannot search is not a missing lock. Depending on the Python
        version the SDK either raises a `PermissionError` or, through `is_file()`, reports no lock at all; the
        gate names the permission error either way, rather than saying `codegen.lock — not found`."""
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            pytest.skip("root searches every directory")
        tree = self.write_python_project(tmp_path)
        tree.parent.chmod(0o000)
        try:
            result = self.run_python_gate(tmp_path, "generated/summarize")
        finally:
            tree.parent.chmod(0o755)
        assert result.returncode == 2, self.explain(result)
        assert "  no verdict: the lock check failed — PermissionError: " in result.stderr
        assert "not found" not in result.stderr

    def test_the_python_gate_has_no_verdict_when_the_source_check_raises(self, tmp_path: Path) -> None:
        """The source check reads each recorded source relative to the working directory, and a process whose
        working directory was deleted under it cannot resolve that directory at all. That is no verdict for the
        directory, not the drift an uncaught `FileNotFoundError` would have exited with."""
        sh = shutil.which("sh")
        if sh is None:
            pytest.skip("no sh on the PATH")
        tree = self.write_python_project(tmp_path / "project")
        gate = tmp_path / "codegen_check.py"
        gate.write_bytes((self.REFERENCES_DIR / "codegen_check.py").read_bytes())
        doomed = tmp_path / "doomed"
        doomed.mkdir()
        result = subprocess.run(
            [sh, "-c", 'cd "$1" && rmdir "$1" && exec "$2" "$3" "$4"', "sh", str(doomed), sys.executable, str(gate), str(tree)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 2, self.explain(result)
        assert "  tree current (crate" in result.stderr
        assert "  no verdict: the source check failed — FileNotFoundError: " in result.stderr
        assert result.stdout.endswith("codegen-check: no verdict\n")

    def test_the_python_gate_never_fails_on_a_line_it_prints(self, tmp_path: Path) -> None:
        """A current by-ref tree prints `sources.json records no sources — …`, and under a Latin-1 locale
        with stdout redirected that em dash raised `UnicodeEncodeError`: exit 1 on a tree with nothing wrong.
        The locale is also pinned through `PYTHONIOENCODING`, because a runner that lacks the locale would
        otherwise fall back to UTF-8 and pass without exercising anything. A directory argument holding a
        byte the filesystem encoding cannot decode crashed the same write under UTF-8."""
        tree = self.write_python_project(tmp_path)
        (tree / "sources.json").write_text('{"method": {"method_ref": "github.com/acme/methods@v1"}, "sources": {}}', encoding="utf-8")
        gate = tmp_path / "scripts" / "codegen_check.py"
        gate.parent.mkdir(parents=True)
        gate.write_bytes((self.REFERENCES_DIR / "codegen_check.py").read_bytes())
        environment = {key: value for key, value in os.environ.items() if key not in {"PYTHONUTF8", "PYTHONIOENCODING"}}

        latin = subprocess.run(
            [sys.executable, str(gate), "generated/summarize"],
            cwd=tmp_path,
            env={**environment, "LC_ALL": "en_US.ISO8859-1", "LANG": "en_US.ISO8859-1", "PYTHONIOENCODING": "iso-8859-1"},
            capture_output=True,
            check=False,
        )
        stdout = latin.stdout.decode("iso-8859-1")
        stderr = latin.stderr.decode("iso-8859-1")
        assert latin.returncode == 0, f"exit {latin.returncode}\nstdout: {stdout}\nstderr: {stderr}"
        assert "  sources.json records no sources \\u2014 a by-ref or by-id integration" in stdout
        assert stdout.endswith("codegen-check: current\n")

        undecodable = subprocess.run(
            [sys.executable, str(gate), b"generated/\xff"],
            cwd=tmp_path,
            env={**environment, "PYTHONIOENCODING": "utf-8"},
            capture_output=True,
            check=False,
        )
        assert undecodable.returncode == 2, undecodable.stderr.decode("utf-8", errors="replace")
        assert undecodable.stdout.decode("utf-8").startswith("generated/\\udcff\n")
        assert b"Traceback" not in undecodable.stderr

    def test_the_python_gate_imports_only_the_standard_library_and_the_sdk(self) -> None:
        """What a consumer's project already has is all the script may need, and it keeps the two
        decoding choices that make it refuse what the TypeScript gate refuses."""
        script = (self.REFERENCES_DIR / "codegen_check.py").read_text(encoding="utf-8")
        imported: list[str] = []
        for node in ast.walk(ast.parse(script)):
            if isinstance(node, ast.Import):
                imported.extend(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom):
                imported.append(node.module or "")
        assert imported, "the script should import something"
        for module in imported:
            top_level = module.split(".")[0]
            assert top_level == "pipelex_sdk" or top_level in sys.stdlib_module_names, f"unexpected import: {module}"
        assert "from pipelex_sdk.codegen_check import run_codegen_check" in script
        assert "sys.stdout.write" in script and "sys.stderr.write" in script
        assert "print(" not in script
        # A BOM stays in the decoded sidecar, so `json.loads` refuses it; `utf-8-sig` would strip it.
        assert '.read_bytes().decode("utf-8")' in script
        assert '.decode("utf-8-sig")' not in script
        assert "json.loads(text, parse_constant=_reject_json_constant)" in script
        # Two broad catches: one around the SDK import, whose failures at load are open-ended, and one inside
        # `settle`, around each check. Neither reaches `BaseException`, so an interrupt stays an interrupt.
        # And a stream that escapes what it cannot encode.
        assert script.count("except Exception") == 2
        assert "except BaseException" not in script
        assert script.index("except ImportError as import_error:") < script.index("except Exception as load_error:")
        assert 'settle(name="lock", check=partial(check_tree, directory=directory))' in script
        assert 'settle(name="source", check=partial(check_sources, directory=directory))' in script
        assert 'stream.reconfigure(errors="backslashreplace")' in script

    def test_the_check_script_imports_only_node_builtins_and_the_sdk(self) -> None:
        script = (self.REFERENCES_DIR / "codegen-check.mjs").read_text(encoding="utf-8")
        imports = re.findall(r'^import .* from "([^"]+)";$', script, flags=re.MULTILINE)
        assert imports, "the script should import through static ESM imports"
        for module in imports:
            assert module.startswith("node:") or module == "@pipelex/sdk", f"unexpected import: {module}"
        # The SDK is imported dynamically, inside a catch that turns its absence into no verdict. A static
        # import of it fails before any line of the script runs, and that uncaught failure exits 1: drift.
        assert "@pipelex/sdk" not in imports
        assert re.findall(r'\bimport\(\s*"([^"]+)"\s*\)', script) == ["@pipelex/sdk"]
        assert "runCodegenCheck" in script and "isStampableArtifactPath" in script
        assert "process.stdout.write" in script and "process.stderr.write" in script
        assert "console." not in script

    def test_the_typescript_sdk_floor_is_one_number_everywhere(self) -> None:
        """Step 8 names the `@pipelex/sdk` floor and raises an older pin to it, as it does for `pipelex-sdk`, and
        every other place that names a TypeScript SDK version names the same one: the step 10 bullet, the failure
        row, refresh mode, the reference, the gate's `SDK_MINIMUM` and the changelog. A bump that updates one and
        misses another fails here, on the place it missed."""
        body = self.integrate
        step_8 = self.the_line(body, "With the project's own package manager (read the lockfile):")
        clause = re.search(r"`zod` and `@pipelex/sdk` for TypeScript — at least `@pipelex/sdk` (\S+), (.*?); `pydantic`", step_8)
        assert clause, "step 8 names no @pipelex/sdk floor"
        assert clause.group(1) == self.TYPESCRIPT_SDK_FLOOR
        assert "so an older pin already in the project is raised and the report says so" in clause.group(2)

        # Every version these TypeScript-only regions carry is the floor, and each carries it at least once.
        regions = {
            "step 10's TypeScript bullet": self.the_line(body, "- **TypeScript**: copy [references/codegen-check.mjs]"),
            "the failure row": self.the_line(body, "| the TypeScript gate exits `2` saying `@pipelex/sdk` is not importable"),
        }
        typescript = (self.REFERENCES_DIR / "typescript.md").read_text(encoding="utf-8")
        for index_line, line in enumerate(typescript.splitlines()):
            if "@pipelex/sdk" in line and self.VERSION.search(line):
                regions[f"typescript.md line {index_line + 1}"] = line
        assert len(regions) >= 4, "typescript.md should name the floor in its header and its offline gate section"
        for where, text in regions.items():
            assert set(self.VERSION.findall(text)) == {self.TYPESCRIPT_SDK_FLOOR}, f"{where} names {self.VERSION.findall(text)}"

        # Refresh mode names no number: it defers to step 8, so it cannot fall behind a bump.
        refresh_dependencies = (
            "the dependencies (except an `@pipelex/sdk`, or a `python-pydantic` project's `pipelex-sdk`, "
            "pinned below step 8's floor, raised as step 8 raises it"
        )
        assert refresh_dependencies in self.refresh_cells(body)["left alone"]

        gate = (self.REFERENCES_DIR / "codegen-check.mjs").read_text(encoding="utf-8")
        assert f'const SDK_MINIMUM = "{self.TYPESCRIPT_SDK_FLOOR}";' in gate
        assert self.VERSION.findall(gate) == [self.TYPESCRIPT_SDK_FLOOR], "the gate names a version other than SDK_MINIMUM"

        changelog = self.the_line((self.REPO_ROOT / "CHANGELOG.md").read_text(encoding="utf-8"), "**`pipelex-integrate` — wire an MTHDS method")
        assert re.findall(r"`@pipelex/sdk` (\d+\.\d+\.\d+)", changelog) == [self.TYPESCRIPT_SDK_FLOOR]

        # What a user installs: the committed skill of every target carries step 8's floor.
        for target_name in ("prod", "codex", "mistral-vibe"):
            config = load_target_config(self.REPO_ROOT / "targets", target_name)
            installed = (resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate" / "SKILL.md").read_text(encoding="utf-8")
            assert f"`zod` and `@pipelex/sdk` for TypeScript — at least `@pipelex/sdk` {self.TYPESCRIPT_SDK_FLOOR}," in installed, target_name

    def refresh_cells(self, body: str) -> dict[str, str]:
        """Refresh mode's table, its one body row cut into its three cells, keyed by the header it sits under."""
        header = self.the_line(body, "| Taken from disk |")
        assert header == "| Taken from disk | Re-derived and re-checked | Left alone |", header
        row = self.the_line(body, "| the selector, target, destination and `pipe` record")
        cells = [cell.strip() for cell in row.split(" | ")]
        assert len(cells) == 3, f"the refresh row should have three cells, found {len(cells)}: {row!r}"
        return {"taken from disk": cells[0].removeprefix("| "), "re-checked": cells[1], "left alone": cells[2].removesuffix(" |")}

    # What refresh does to the drift gate, pinned in the template and in every target's committed skill. A
    # refresh used to leave the gate wiring alone except to install a missing Python script, so on a project
    # whose methods A and B predate the gate, refreshing A installed it and registered A, and refreshing B found
    # the script present and never registered B — and no refresh ever replaced a gate script an earlier version
    # of the skill had copied, such as a `codegen-check.mjs` that exits 1 when its SDK is missing.
    REFRESH_GATE_RULES = (
        "**the drift gate of the refreshed method's language**, re-checked against step 10 on every refresh",
        "`scripts/codegen-check.mjs` for `ts-zod`, `scripts/codegen_check.py` for `python-pydantic`",
        "**a missing script is installed and wired as step 10 does**",
        "**a script that differs byte for byte from the reference is re-copied verbatim**",
        "**the refreshed method's generated directory is added to the gate command's arguments when it is not among them**",
        "each said in the report",
        "for `python-structures` there is no script to copy, so only the last applies, to its `pipelex codegen check` wiring",
    )
    REFRESH_REFERENCE_RULE = (
        "on a refresh add the refreshed method's directory when it is missing, leaving the others as they are. "
        "A refresh also re-copies the script when the project's copy differs from this reference, and installs it when the project has none"
    )

    @pytest.mark.parametrize("target_name", ["template", "prod", "codex", "mistral-vibe"])
    def test_refresh_brings_the_gate_up_to_date_and_registers_the_refreshed_method(self, target_name: str) -> None:
        """Refresh re-checks the gate as step 10 would install it — script present, script current, the refreshed
        directory registered — and leaves every other method's tree and registration alone."""
        if target_name == "template":
            body = self.integrate
        else:
            config = load_target_config(self.REPO_ROOT / "targets", target_name)
            body = (resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate" / "SKILL.md").read_text(encoding="utf-8")
        cells = self.refresh_cells(body)
        for rule in self.REFRESH_GATE_RULES:
            assert rule in cells["re-checked"], f"{target_name}: the refresh table no longer re-checks the gate this way: {rule!r}"
        left_alone = cells["left alone"]
        assert "other methods' trees and their registrations in the gate" in left_alone
        # The gate is no longer something a refresh leaves alone, with or without the one exception it used to carry.
        assert "the gate wiring" not in left_alone
        assert "integrated before that gate existed" not in body
        assert "bring the drift gate up to step 10" in body

        for reference in ("python.md", "typescript.md"):
            text = (self.REFERENCES_DIR / reference).read_text(encoding="utf-8")
            assert self.REFRESH_REFERENCE_RULE in text, f"references/{reference} still registers a directory only as it is integrated"
        changelog = self.the_line((self.REPO_ROOT / "CHANGELOG.md").read_text(encoding="utf-8"), "**`pipelex-integrate` — wire an MTHDS method")
        assert "A refresh keeps the gate current as well:" in changelog

    # Why the gate script is excluded, said in both references: formatted once, it differs from the reference
    # forever, so every refresh re-copies the unformatted bytes and the project's own format check goes red.
    GATE_SCRIPT_EXCLUSION_REASON = (
        "a refresh compares it byte for byte with this reference, so a reformat would make every refresh re-copy it "
        "and leave the project's own format check failing on `scripts/`"
    )

    @pytest.mark.parametrize("target_name", ["template", "prod", "codex", "mistral-vibe"])
    def test_the_copied_gate_script_is_excluded_like_the_generated_tree(self, target_name: str) -> None:
        """The gate script is copied verbatim and refresh re-copies one that differs byte for byte from the
        reference, while refresh never runs the formatter. Left inside a project's `ruff format --check` or
        `prettier --check`, the first integration formats the copy and every later refresh finds it different,
        re-copies the unformatted reference and leaves the project's own format check failing. So step 5 and
        both references put each script in the formatter and linter exclusions, and step 11 never formats it."""
        if target_name == "template":
            body = self.integrate
            references = self.REFERENCES_DIR
        else:
            config = load_target_config(self.REPO_ROOT / "targets", target_name)
            installed = resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate"
            body = (installed / "SKILL.md").read_text(encoding="utf-8")
            references = installed / "references"

        step_5 = self.the_line(body, "Add the generated directory to the formatter's and linter's ignore lists")
        both_scripts = (
            "and with it the gate script step 10 will copy — "
            "`scripts/codegen-check.mjs` for `ts-zod`, `scripts/codegen_check.py` for `python-pydantic`"
        )
        assert both_scripts in step_5, f"{target_name}: step 5 no longer excludes each gate script"
        assert "The script's entry goes in now as well, before the script exists" in step_5
        # The type checker is not told to exclude the script: only the tree's coverage is confirmed.
        assert "while leaving its coverage of the script as it is" in step_5
        assert "Do this **before** step 6" in step_5

        for bullet in ("- **TypeScript**: copy [references/codegen-check.mjs]", "- **Python, `python-pydantic`**:"):
            assert "**never formatted or linted**, which step 5's exclusion keeps true" in self.the_line(body, bullet), f"{target_name}: {bullet}"

        step_11 = self.the_line(body, "Run the project's formatter **on the files you wrote only**")
        assert "never on the generated tree or the gate script step 10 copied;" in step_11, f"{target_name}: step 11 formats the gate script"

        cells = self.refresh_cells(body)
        exclusions_first = "each compared and copied only after the tooling exclusions are verified to name it"
        assert exclusions_first in cells["re-checked"], f"{target_name}: refresh re-copies the gate before verifying its exclusion"
        left_alone = (
            "the tooling exclusions for the generated directory and, where step 10 copies one, "
            "the gate script (verified before the gate is re-checked"
        )
        assert left_alone in cells["left alone"], f"{target_name}: refresh's exclusions no longer cover the gate script"

        python = (references / "python.md").read_text(encoding="utf-8")
        python_row = self.the_line(python, "| **Formatter and linter** |")
        assert "`[tool.ruff]` → add the generated directory and the gate script `scripts/codegen_check.py`" in python_row
        assert "`[tool.black]` → `extend-exclude`, one regex matching both" in python_row
        assert "`[tool.isort]` → both in `skip` / `extend_skip_glob`" in python_row
        assert 'extend-exclude = ["<package>/generated", "scripts/codegen_check.py"]' in python
        assert "extend-exclude = '^/(<package>/generated/|scripts/codegen_check\\.py$)'" in python
        assert 'extend_skip_glob = ["<package>/generated/*", "scripts/codegen_check.py"]' in python
        assert "codegen_check" not in self.the_line(python, "| **Type checker still covers the tree** |")

        typescript = (references / "typescript.md").read_text(encoding="utf-8")
        formatter_row = self.the_line(typescript, "| **Formatter** |")
        assert "add `src/generated/` and the gate script `scripts/codegen-check.mjs` to `.prettierignore`" in formatter_row
        assert '`"!scripts/codegen-check.mjs"`' in formatter_row and '`"scripts/codegen-check.mjs"` before Biome 2' in formatter_row
        linter_row = self.the_line(typescript, "| **Linter** |")
        assert 'add `"src/generated/**"` and `"scripts/codegen-check.mjs"` to `globalIgnores([...])`' in linter_row
        assert "the same two lines in `.eslintignore`" in linter_row
        assert "codegen-check" not in self.the_line(typescript, "| **Type checker still covers the tree** |")

        for reference, text in (("python.md", python), ("typescript.md", typescript)):
            assert self.GATE_SCRIPT_EXCLUSION_REASON in text, f"{target_name}: references/{reference} no longer says why the script is excluded"

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_every_platform_renders_the_skill_and_its_references(self, target_name: str) -> None:
        config = load_target_config(self.REPO_ROOT / "targets", target_name)
        body = self.render(target_name)
        assert "# Integrate an MTHDS method into a codebase" in body
        assert "{%" not in body
        assert "{{" not in body
        for rule in self.RULES:
            assert rule in body, f"{target_name}: missing rule: {rule}"
        if target_name == "prod":
            assert "mcp__plugin_pipelex_pipelex__mthds_codegen" in body
            assert "offer `/pipelex-scaffold`" in body
        else:
            assert "mcp__" not in body
            assert "open `../pipelex-scaffold/SKILL.md`" in body

        references_dir = resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate" / "references"
        for reference in self.REFERENCES:
            assert (references_dir / reference).is_file(), f"{target_name}: missing references/{reference}"

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_the_committed_references_match_the_source_byte_for_byte(self, target_name: str) -> None:
        """The references are executable know-how, and the committed target copies are the ones a
        user installs — so compare against those, not against a fresh `copytree` into a tmp dir,
        which only ever asserts that `shutil` copies bytes. A stale committed copy is the whole
        failure mode, and it is invisible to any assertion that rebuilds its own expected side.
        """
        config = load_target_config(self.REPO_ROOT / "targets", target_name)
        installed = resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate" / "references"
        for reference in self.REFERENCES:
            assert (installed / reference).is_file(), f"{target_name}: missing references/{reference}"
            assert (installed / reference).read_bytes() == (self.REFERENCES_DIR / reference).read_bytes(), (
                f"{target_name}: references/{reference} is stale — run `make build`"
            )
