"""Pin the load-bearing rules of the pipelex-integrate skill template and its references."""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

from scripts.gen_skill_docs import load_target_config, render_templates, resolve_output_dir


class TestPipelexIntegrateSkill:
    """The skill is executable guidance, so these tests guard the rules a user's
    codebase depends on: the write arm is the only arm, generated bytes are never
    touched, one directory per method, orphans are never deleted, sources are never
    mixed, a project-owned harness is kept, and the signature comes from the verdict.
    """

    REPO_ROOT = Path(__file__).parents[2]
    TEMPLATE = REPO_ROOT / "templates" / "skills" / "pipelex-integrate" / "SKILL.md.j2"
    REFERENCES_DIR = REPO_ROOT / "skills" / "pipelex-integrate" / "references"
    REFERENCES = ("typescript.md", "python.md", "codegen-check.mjs")
    RULES = (
        "**The write arm, always.** Every `mthds_codegen` call passes `output_dir`.",
        "never by calling again without `output_dir` and writing the returned bytes yourself",
        "**Generated files are never opened for editing, never formatted, never linted.**",
        "**One directory per method.**",
        "You never delete an orphan either",
        "**Never generate from one source and run from another.**",
        "**A project that owns a codegen harness keeps it.** Never write a second generated layout",
        "**No `dropWireNulls` / `wireOutput` helper.**",
        "Do this **before** step 6",
        "**Check containment before the call rather than waiting for an error**",
        "never write the tree into the workshop's own directory and move it across afterwards",
        # The run route takes the bare pipe code; the verdict and the sidecar carry the namespaced ref.
        "**`pipe_ref` and the run's `pipe_code` are not the same string**",
        # A bundle is one closure: the call site submits every file, not just main.mthds.
        "It loads **every `.mthds` file of the committed bundle** at call time",
        # The containment reading is lexically wrong in both directions without resolving.
        "**Resolve both sides before comparing them**",
        "**Both inputs are known as soon as step 1 names the project, so do this reading there**",
        # A lock with no sidecar is also what this method's own interrupted run leaves.
        "**One lock-without-sidecar is this method's own, and relocating is the wrong answer for it**",
        # The harness keeps no sidecar by design, so step 4's rule cannot govern its layout.
        "**This is the one destination step 4's sidecar rule does not govern**",
        # A list output arrives as an array and a single-object parser rejects it.
        "**Narrow according to the output's `multiplicity`, which step 3 recorded**",
    )

    # The closed set of ways an instruction to end the run can be written. The continuing regions —
    # step 6's orphans branch, its failure-table row, refresh mode — are written without any of
    # them, and "do nothing else" is in the set because that is the phrase the decision struck, so
    # restoring it fails here instead of passing as a clarification of an unchanged rule.
    HALT_VOCABULARY = re.compile(r"\b(?:stop|stops|stopped|stopping|abort|aborts|aborting|halt|halts|do nothing else)\b", re.IGNORECASE)

    # How a region says the run proceeds past a write the check marks non-current. Used to FIND the
    # continuing regions rather than to spell them, so the condition assertions below reach whatever
    # those regions are later reworded into rather than only the wording in front of them now.
    CONTINUE_VOCABULARY = re.compile(
        r"carry on|carries on|continue to step|continues|runs on through|does not end (?:the run|a refresh)",
        re.IGNORECASE,
    )

    # The two halves of the ruled condition, each in the forms it may legitimately take: the branch
    # headers read "`orphans[]` non-empty and `drifts[]` empty", the refresh sentence reads "a
    # non-empty `orphans[]` with an empty `drifts[]`". Both halves must appear wherever the run
    # continues — dropping the `drifts[]` half is exactly what turns the branch back into the
    # blanket exemption that no gate could reach.
    ORPHANS_NON_EMPTY = re.compile(r"`orphans\[\]`[^.|]{0,40}non-empty|non-empty[^.|]{0,40}`orphans\[\]`", re.IGNORECASE)
    DRIFTS_EMPTY = re.compile(r"`drifts\[\]`[^.|]{0,40}(?<!non-)empty|(?<!non-)empty[^.|]{0,40}`drifts\[\]`", re.IGNORECASE)

    # The two halves searched for separately are not the condition, and a region can satisfy both
    # while stating neither as its condition: step 6's branch reads `drifts[]` three times, so
    # striking `and `drifts[]` empty` from its header leaves the later, non-conditional mentions to
    # answer `DRIFTS_EMPTY` — and the branch is the blanket exemption again with the suite green.
    # This pins the conjunction inside one clause, which is the only place it decides anything.
    CONDITION = re.compile(
        r"`orphans\[\]`[^.|]{0,30}non-empty[^.|]{0,30}`drifts\[\]`[^.|]{0,30}(?<!non-)empty"
        r"|non-empty[^.|]{0,30}`orphans\[\]`[^.|]{0,30}(?<!non-)empty[^.|]{0,30}`drifts\[\]`",
        re.IGNORECASE,
    )

    # `orphans[]` is always present and empty when clean; `drifts[]` is present only when non-empty
    # (`pipelex-mcp/SPEC.md` → `drifts?: unknown[]; // present when non-empty`). So the field the
    # continuing branch is read off is ABSENT in exactly the case that branch must recognise, and a
    # region telling an agent to read two lists owes it that the missing one is the empty one.
    ABSENT_DRIFTS_IS_EMPTY = re.compile(r"present only when (?:it is )?non-empty", re.IGNORECASE)

    # Continuing leaves the step-10 gate red, which is the consequence the report owes the user — but
    # step 10 installs no gate at all for a `python-pydantic` consumer, so an unqualified claim tells
    # that user a check that does not exist is failing, and step 12 would say both things at once.
    GATE_ONLY_WHERE_INSTALLED = re.compile(r"where the project has one|where a gate was installed|gets a gate at all", re.IGNORECASE)

    # `is_current` is `false` on the continuing branch and on the stopping one alike, so a region
    # that continues has to say it is not what the branch is read from. This is the assertion the
    # first implementation lacked altogether, which is how a continue branch an agent could never
    # reach — it checks `is_current`, finds `false`, and stops — stayed green through a whole round.
    NOT_THE_VERDICT = re.compile(r"never (?:from )?`is_current`", re.IGNORECASE)

    # A mention of overwriting inside a continuing region is admissible only as a denial: the
    # hazardous case reports an EMPTY `orphans[]`, because every method of a target emits the same
    # file names, so the files that would be clobbered are overwritten without being reported at all.
    OVERWRITE_DENIAL = re.compile(r"\b(?:never|cannot|none|without)\b", re.IGNORECASE)

    @property
    def integrate(self) -> str:
        return self.TEMPLATE.read_text(encoding="utf-8")

    def render(self, target_name: str) -> str:
        """The skill as the named target renders it — what a user of that harness installs."""
        config = load_target_config(self.REPO_ROOT / "targets", target_name)
        rendered = render_templates(
            self.REPO_ROOT / "templates",
            self.REPO_ROOT,
            config.template_vars,
            include_skills=["pipelex-integrate"],
            target_name=config.name,
        )
        return next(content for path, content in rendered.items() if path.match("skills/pipelex-integrate/SKILL.md"))

    @staticmethod
    def the_line(body: str, needle: str) -> str:
        """The one line carrying `needle`. Two of them is a duplicated rule, which is its own defect."""
        lines = [line for line in body.splitlines() if needle in line]
        assert len(lines) == 1, f"expected exactly one line containing {needle!r}, found {len(lines)}"
        return lines[0]

    def test_the_rules_that_never_bend_are_stated(self) -> None:
        body = self.integrate
        for rule in self.RULES:
            assert rule in body, f"missing rule: {rule}"

    def test_signature_comes_from_the_verdict_and_the_heuristic_is_absent(self) -> None:
        body = self.integrate
        assert "A valid verdict carries **`main_pipe`**" in body
        assert "**`explicit: true`** — the one call in this plugin that wants the ceremonial" in body
        # The by-elimination output-concept heuristic was designed, then made obsolete before it shipped.
        assert "candidate output concepts" not in body
        assert "minus the input concepts minus natives" not in body
        # A by-ref / by-id source with no signature stops instead of guessing.
        assert "STOP and say the verdict carries no signature to type this integration exactly" in body
        # The entry pipe is the verdict's, which follows a package manifest; its absence has three causes, not one.
        assert "`main_pipe.pipe_ref` is the pipe a run with no pipe selector executes" in body
        assert "the method settles **no entry pipe**" in body
        assert "the workshop **predates the signature**" in body
        # The third cause was stated in step 3 but dropped from the failure table, whose remedy differs by cause.
        assert "the entry pipe's contract did not come back whole, which comes from the runner" in body
        # The same signature rides the text summary, so a host that drops structured content is not a dead end.
        assert "the **same fact on a second channel, not a fourth cause**" in body

    def test_the_wire_null_helper_is_never_installed(self) -> None:
        body = self.integrate
        assert "wire-output.ts" not in body
        assert "wireOutput(results" not in body
        for reference in self.REFERENCES:
            assert "dropWireNulls" not in (self.REFERENCES_DIR / reference).read_text(encoding="utf-8")

    def test_the_helper_budget_is_one_and_does_not_license_a_second(self) -> None:
        """The budget was two while the wire-output helper was the second. That helper was struck for
        being lossy and is forbidden outright below, so a surviving "at most two" is not merely a
        stale count — it is written permission to create the one thing the campaign removed, in a
        sentence that then says "and nothing else" about a list of one.
        """
        body = self.integrate
        assert "**Exactly one shared helper, created once per project" in body
        assert "one callable module per method plus one shared helper" in body
        assert "two shared helpers" not in body
        assert "at most two" not in body
        decisions = (self.REPO_ROOT / "docs" / "decisions.md").read_text(encoding="utf-8")
        assert "two shared helpers" not in decisions

    def test_failure_posture_pins_the_403_and_the_orphans(self) -> None:
        body = self.integrate
        assert "a **403** on `mthds_codegen` is a feature gate, not a key problem" in body
        assert 'never say "check your key" for a 403' in body
        assert '`kind: "paywall"`' in body
        assert "Report the orphan paths by name, never delete one" in body
        assert "never delete, move or clear the named file" in body
        assert "and never offer to" in body
        # A lock is not this method's without a sidecar naming it: same file names mean a silent overwrite, not an orphan.
        assert "is this method's only when a `sources.json` beside it names this method" in body
        assert "would silently overwrite the other method's stamped files rather than report an orphan" in body
        assert "report `drifts[]` verbatim and stop" in body
        # The emitter's extensionless import is a known defect: named, never patched in the stamped tree.
        assert 'a known defect of the ts-zod emitter, which writes `from "./types"`' in body
        assert "Changing the project's `moduleResolution` is the user's call to make, not yours" in body

    def continuing_regions(self, body: str) -> dict[str, str]:
        """Every region that tells the agent to proceed past a write the check marks non-current,
        keyed by where it is. Cut out by its anchor rather than searched for by the sentence under
        test, so the assertions apply to the region as a whole.
        """
        orphans = self.the_line(body, "- Success with **`orphans[]` non-empty")
        row = self.the_line(body, "| success with `orphans[]` non-empty")
        # Refresh mode's rule is one sentence run of a long paragraph, so cut it out rather than
        # scanning the paragraph — the rest of it is about content hashes and the call site.
        opens = "**A non-empty `orphans[]` with an empty `drifts[]` does not end a refresh either**"
        closes = "still ends the refresh, there as here."
        paragraph = self.the_line(body, opens)
        start = paragraph.index(opens)
        refresh = paragraph[start : paragraph.index(closes, start) + len(closes)]
        return {"step 6's orphans branch": orphans, "the failure table's orphans row": row, "refresh mode": refresh}

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_the_run_continues_on_orphans_alone_and_on_nothing_else(self, target_name: str) -> None:
        """Re-ruled by the founder on 2026-09-13 (`L-260912-3d5693`), replacing an earlier ruling of
        the same day that a review proved unimplementable. **The run continues when `orphans[]` is
        non-empty and `drifts[]` is empty, read off those two fields and never inferred from
        `is_current`; anything that also drifted ends the run.**

        What this test guards is the *condition*, because the condition is the whole decision and its
        absence is what made the first implementation green and wrong. `pipelex-mcp` sets
        `is_current: false` the moment a directory holds an orphan, so there is no
        success-with-orphans verdict to branch on: a branch phrased on the verdict is unreachable,
        and a branch phrased on nothing is a blanket exemption that swallows real drift. So every
        region that tells the agent to carry on must name both halves of the condition and must say
        the verdict is not what distinguishes them, and the stopping branch must claim every other
        false verdict. Asserting the continue wording exists — which is all the first test did —
        proves none of that.
        """
        body = self.render(target_name)
        regions = self.continuing_regions(body)

        for where, region in regions.items():
            assert self.CONTINUE_VOCABULARY.search(region), f"{target_name}: {where} no longer tells the agent to proceed"
            assert self.ORPHANS_NON_EMPTY.search(region), f"{target_name}: {where} continues without requiring a non-empty `orphans[]`"
            assert self.DRIFTS_EMPTY.search(region), (
                f"{target_name}: {where} continues without requiring an empty `drifts[]` — the ruled condition is gone "
                f"and the branch is the blanket exemption again: {region!r}"
            )
            assert self.CONDITION.search(region), (
                f"{target_name}: {where} names both halves somewhere but states neither as the condition it branches on, "
                f"which is the blanket exemption wearing the condition's vocabulary: {region!r}"
            )
            assert self.ABSENT_DRIFTS_IS_EMPTY.search(region), (
                f"{target_name}: {where} sends the agent to read `drifts[]` without saying it is present only when "
                f"non-empty, so the field the branch turns on is absent in exactly the case the branch is for: {region!r}"
            )
            assert self.NOT_THE_VERDICT.search(region), (
                f"{target_name}: {where} does not say the branch is read off the two lists and never from `is_current`, "
                f"which is `false` on both branches, so an agent reading the verdict takes the stopping one: {region!r}"
            )
            halt = self.HALT_VOCABULARY.search(region)
            assert halt is None, f"{target_name}: {where} ends the run ({halt.group(0)!r} in {region!r})"

        # The stopping branch claims every false verdict the condition above does not, so the two are
        # exhaustive: an agent holding a result with any non-orphan drift has exactly one branch.
        stops = self.the_line(body, "- Success with **`is_current: false` for any reason the branch above does not claim**")
        assert "a non-empty `drifts[]`, with or without orphans beside it" in stops
        assert self.HALT_VOCABULARY.search(stops), f"{target_name}: the non-orphan-drift branch no longer ends the run"
        stop_row = self.the_line(body, "| success with `is_current: false` for any other reason |")
        assert self.HALT_VOCABULARY.search(stop_row), f"{target_name}: the failure table's drift row no longer ends the run"
        assert "never commit a tree the check rejects" in stops

        # The success gate and the never-bend rule were right before the decision and the ruling
        # agrees with them: a clean tree is both fields, and two generations in one directory are
        # non-current by design. The gate also has to reach the branches that carry its two failures.
        gate = self.the_line(body, '- `status: "ok"`, `is_valid: true`, and `output_dir` present')
        assert "Confirm **`is_current: true`** and an empty **`orphans[]`**" in gate
        assert "the two branches below carry the two cases where it is not" in gate
        assert "two methods in one directory therefore read as permanently non-current, by design" in body

        # Step 4 enumerates the stops that leave a lock with no sidecar. Orphans alone is not one of
        # them any more, and the `is_current: false` item is qualified so the sentence stays true.
        assert "every stop between them — an `is_current: false` that step 6 does not let through, a partial write whose retry also failed —" in body

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_no_continuing_region_claims_an_overwrite_the_signal_cannot_show(self, target_name: str) -> None:
        """The first ruling made a loud report the whole protection against another method's
        same-named files having been overwritten by the write that just succeeded. Step 4 of this
        same skill says why that cannot be: every method of a target emits the same file names, so
        generating into a shared directory overwrites the other method's stamped files *rather than
        reporting an orphan*. A non-empty `orphans[]` therefore appears only where the prior tree
        held files this generation does not emit — which is exactly where nothing was clobbered.

        So a continuing region may mention overwriting only to rule it out, and what it owes instead
        is what the signal does mean: artifacts this generation does not list, none deleted, a
        dedicated directory per generation as the fix, and the gate red until the directory holds one
        generation. Step 12 is included because the run now provably reaches it and that is where
        the user reads any of this.
        """
        body = self.render(target_name)
        regions = dict(self.continuing_regions(body))
        regions["step 12's report"] = self.the_line(body, "What was generated and where; the target and why;")

        for where, region in regions.items():
            for found in re.finditer(r"overwr\w+", region):
                preceding = region[max(0, found.start() - 140) : found.start()]
                assert self.OVERWRITE_DENIAL.search(preceding), (
                    f"{target_name}: {where} states an overwrite as a possibility, which a non-empty `orphans[]` "
                    f"cannot show: {region[max(0, found.start() - 140) : found.end() + 80]!r}"
                )

        for where, region in regions.items():
            assert "this generation does not list" in region, f"{target_name}: {where} does not say what an orphan actually is"
            assert "dedicated directory per generation" in region, f"{target_name}: {where} drops the remedy"
        assert "none of them deleted" in regions["step 6's orphans branch"]
        assert "never delete one" in regions["the failure table's orphans row"]
        assert "never deletes them" in regions["refresh mode"]
        assert "none of them were deleted" in regions["step 12's report"]

        # Continuing leaves the gate this skill installs red, because that gate counts an orphan as a
        # drift — and the one way to turn it green is the deletion the never-bend rules forbid.
        assert "exits non-zero on this directory until it holds one generation" in regions["step 6's orphans branch"]
        assert "deleting an orphan to turn it green is the one remedy forbidden above" in regions["step 6's orphans branch"]
        assert "counts each as a drift until it holds one generation" in regions["the failure table's orphans row"]
        assert "the gate stays non-zero on that directory until it holds one generation" in regions["refresh mode"]
        assert "counts each one as a drift" in regions["step 12's report"]

        # Every region that makes the gate claim qualifies it, because one of the three targets gets
        # no gate: step 10 installs none for a `python-pydantic` consumer, where the refresh is the
        # whole guard. Unqualified, step 12 would tell that user in one breath that the gate counts
        # each orphan as a drift and that no offline drift check exists.
        # Keyed on the claim and not on the step number: refresh mode makes it as "the gate stays
        # non-zero" without naming step 10 at all, so a guard spelled `"step 10" in region` skips the
        # one region whose wording does not carry the number.
        for where, region in regions.items():
            if "gate" not in region:
                continue
            assert self.GATE_ONLY_WHERE_INSTALLED.search(region), (
                f"{target_name}: {where} claims the step-10 gate counts the orphans without saying the project may "
                f"have no gate — which a `python-pydantic` consumer does not: {region!r}"
            )

        # Partial detection stays partial detection rather than a clean tree.
        assert "say orphan detection was partial rather than reporting a clean tree" in regions["step 6's orphans branch"]
        for where in ("the failure table's orphans row", "refresh mode"):
            assert "`orphans_truncated: true` → say detection was partial" in regions[where]

        # The struck sentences of both superseded rulings, neither of which may come back.
        for struck in (
            "do nothing else",
            "the check owns the tree",
            "the check says the tree is current",
            "may therefore have been overwritten by the write that just succeeded",
            "this write may have overwritten same-named files of another method",
            "the regeneration has overwritten the other method's same-named files again",
        ):
            assert struck not in body, f"{target_name}: a struck phrase is back in the skill: {struck!r}"

    def test_the_call_sites_submit_the_whole_bundle_not_just_main(self) -> None:
        """Generation takes every `.mthds` file of the bundle, so the run must too.

        A call site that submits `main.mthds` alone type-checks, passes the offline gate, and then
        fails at load time on exactly the multi-file methods codegen handled correctly.
        """
        typescript = (self.REFERENCES_DIR / "typescript.md").read_text(encoding="utf-8")
        assert "mthds_contents: await readBundle()," in typescript
        # An interface has no implicit index signature, so it is not assignable to Record<string, unknown>.
        assert "export type SummarizePdfInputs = {" in typescript
        assert "export interface SummarizePdfInputs" not in typescript
        assert "**`SummarizePdfInputs` is a `type`, not an `interface`, and that is load-bearing.**" in typescript
        # A script merely named `codegen` is not evidence of a Pipelex harness.
        assert "read the script before believing it" in typescript
        assert 'name.endsWith(".mthds")' in typescript
        assert "mthds_contents: [bundle]" not in typescript
        # Its own relative imports need extensions on the resolution that meets the emitter defect.
        assert "**The three relative imports above are extensionless, which is correct only on a bundler resolution.**" in typescript

        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        assert "mthds_contents=_read_bundle()," in python
        assert 'sorted(BUNDLE_DIR.rglob("*.mthds"))' in python
        assert "BUNDLE_PATH" not in python

    def test_the_gate_fails_closed_on_a_malformed_sources_and_does_not_truncate(self) -> None:
        """The offline gate is the one executable artifact here, so two properties are pinned.

        A sidecar whose `sources` is present but not an object must fail the way an unreadable one
        does: coerced to `{}` it would check nothing, print nothing and exit 0 — the single input
        that is both silent and green. And the verdict's explanation must survive a pipe, which
        `process.exit` does not guarantee.
        """
        gate = (self.REFERENCES_DIR / "codegen-check.mjs").read_text(encoding="utf-8")
        # Neither `??` nor `?.` on the way to `sources`: both turn a hostile value into the
        # legitimate absent case. `?.` is the subtler of the two — a sidecar whose whole content is
        # `null`, `[]`, `"x"` or `42` is valid JSON and not an object, and `sidecar?.sources` makes
        # every one of them `undefined`, so the gate claims "a by-ref or by-id integration" and
        # exits 0 over a file that says nothing of the kind. Guard the sidecar, then its `sources`.
        assert "const sources = sidecar.sources;" in gate
        assert "const sources = sidecar?.sources" not in gate
        assert "?? {}" not in gate
        assert 'if (typeof sidecar !== "object" || sidecar === null || Array.isArray(sidecar)) {' in gate
        assert "not a JSON object, so staleness cannot be ruled out" in gate
        assert 'if (typeof sources !== "object" || sources === null || Array.isArray(sources)) {' in gate
        assert "is not an object, so staleness cannot be ruled out" in gate
        # No branch is both silent and green: absent and empty both announce themselves.
        assert "records no sources — a by-ref or by-id integration; source staleness does not apply" in gate
        assert "process.exitCode = await main(process.argv);" in gate
        # The default decoder strips a BOM, which would hash a BOM'd artifact as current.
        assert 'new TextDecoder("utf-8", { fatal: true, ignoreBOM: true })' in gate
        assert "process.exit(await main" not in gate

    @pytest.mark.parametrize(
        ("sidecar", "expected_exit"),
        [
            ("null", 1),
            ("[]", 1),
            ('"a string"', 1),
            ("42", 1),
            ("true", 1),
            ('{"method": {"id": "mt_x"}}', 0),
            ('{"sources": {}}', 0),
            ('{"sources": null}', 1),
            ('{"sources": []}', 1),
        ],
    )
    def test_the_gate_runs_and_refuses_a_non_object_sidecar(self, sidecar: str, expected_exit: int, tmp_path: Path) -> None:
        """Run the gate, do not read it. Every case here was found by executing it, and the
        non-object-sidecar ones reported `current` with exit 0 before the guard went in — the
        failure the file's own header calls its one job to avoid.

        The lock check is made to yield no verdict (no `codegen.lock`), which the script reports on
        its own and which suppresses the sidecar check — so the cases are driven through a tree that
        reaches `checkSources`, i.e. one with a lock. Skipped when no `node` is on the PATH.
        """
        node = shutil.which("node")
        if node is None:
            pytest.skip("no node on the PATH")
        gate = tmp_path / "codegen-check.mjs"
        gate.write_bytes((self.REFERENCES_DIR / "codegen-check.mjs").read_bytes())
        # A lock the SDK cannot even be asked about would short-circuit the sidecar check, so stub
        # the one import and let the tree report itself current.
        stub = tmp_path / "node_modules" / "@pipelex" / "sdk"
        stub.mkdir(parents=True)
        (stub / "package.json").write_text(
            '{"name":"@pipelex/sdk","version":"0.0.0-stub","type":"module","main":"index.js","exports":{".":"./index.js"}}',
            encoding="utf-8",
        )
        (stub / "index.js").write_text(
            "export class CodegenLockError extends Error {}\n"
            "export const isStampableArtifactPath = (p) => p.endsWith('.ts') || p.endsWith('.py');\n"
            "export const runCodegenCheck = async () => ({ isCurrent: true, drifts: [], "
            "crateFingerprint: 'stubfingerprint', engineVersion: '0.0.0' });\n",
            encoding="utf-8",
        )
        tree = tmp_path / "generated" / "m"
        tree.mkdir(parents=True)
        (tree / "codegen.lock").write_text("lock_version = 1\n", encoding="utf-8")
        (tree / "types.ts").write_text("export const x = 1;\n", encoding="utf-8")
        (tree / "sources.json").write_text(sidecar, encoding="utf-8")
        result = subprocess.run(
            [node, str(gate), "generated/m"],
            cwd=tmp_path,
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == expected_exit, (
            f"sidecar {sidecar!r}: expected exit {expected_exit}, got {result.returncode}\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )
        if expected_exit == 0:
            assert "codegen-check: current" in result.stdout
        else:
            assert "codegen-check: drift" in result.stdout

    def test_the_python_call_site_refuses_an_empty_bundle(self) -> None:
        """`Path.rglob` on a missing or empty directory returns nothing and raises nothing, so a
        wrong `BUNDLE_DIR` would submit `mthds_contents=[]` and fail server-side against the pipe
        instead of locally against the path. The TypeScript twin gets this free from `readdir`'s
        ENOENT; the Python one has to ask.
        """
        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        assert "if not contents:" in python
        assert 'raise FileNotFoundError(f"no .mthds files under {BUNDLE_DIR}")' in python

    def test_method_id_warns_and_refresh_leaves_the_call_site_alone(self) -> None:
        body = self.integrate
        assert "The catalog is unversioned" in body
        assert "proceed only on the user's say-so" in body
        assert "**The call site is edited only if it no longer type-checks or the `pipe` record no longer matches the signature**" in body
        assert '"generator": "pipelex-integrate"' in body

    def test_python_gate_asymmetry_is_honest(self) -> None:
        body = self.integrate
        assert "**Python, `python-pydantic`**: **no gate is installed.**" in body
        assert "do not add `pipelex` as a dependency to get a gate" in body
        assert "pipelex codegen check <dir>" in body
        python = (self.REFERENCES_DIR / "python.md").read_text(encoding="utf-8")
        assert "**no gate is installed.**" in python
        assert "there is **no barrel** in `pipelex_sdk` by design" in python

    def test_the_check_script_imports_only_node_builtins_and_the_sdk(self) -> None:
        script = (self.REFERENCES_DIR / "codegen-check.mjs").read_text(encoding="utf-8")
        imports = re.findall(r'^import .* from "([^"]+)";$', script, flags=re.MULTILINE)
        assert imports, "the script should import through static ESM imports"
        for module in imports:
            assert module.startswith("node:") or module == "@pipelex/sdk", f"unexpected import: {module}"
        assert "runCodegenCheck" in script and "isStampableArtifactPath" in script
        assert "process.stdout.write" in script and "process.stderr.write" in script
        assert "console." not in script

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_every_platform_renders_the_skill_and_its_references(self, target_name: str) -> None:
        config = load_target_config(self.REPO_ROOT / "targets", target_name)
        body = self.render(target_name)
        assert "# Integrate an MTHDS method into a codebase" in body
        assert "{%" not in body
        assert "{{" not in body
        for rule in self.RULES:
            assert rule in body, f"{target_name}: missing rule: {rule}"
        if target_name == "prod":
            assert "mcp__plugin_pipelex_pipelex__mthds_codegen" in body
        else:
            assert "mcp__" not in body
        # No project at all is a stop, not an offer: the greenfield front door is not in the
        # published plugin, so naming a skill here would send the user to something absent.
        assert "this is not an integration yet: say so and stop" in body
        assert "pipelex-scaffold" not in body

        references_dir = resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate" / "references"
        for reference in self.REFERENCES:
            assert (references_dir / reference).is_file(), f"{target_name}: missing references/{reference}"

    @pytest.mark.parametrize("target_name", ["prod", "codex", "mistral-vibe"])
    def test_the_committed_references_match_the_source_byte_for_byte(self, target_name: str) -> None:
        """The references are executable know-how, and the committed target copies are the ones a
        user installs — so compare against those, not against a fresh `copytree` into a tmp dir,
        which only ever asserts that `shutil` copies bytes. A stale committed copy is the whole
        failure mode, and it is invisible to any assertion that rebuilds its own expected side.
        """
        config = load_target_config(self.REPO_ROOT / "targets", target_name)
        installed = resolve_output_dir(self.REPO_ROOT, config.source) / "skills" / "pipelex-integrate" / "references"
        for reference in self.REFERENCES:
            assert (installed / reference).is_file(), f"{target_name}: missing references/{reference}"
            assert (installed / reference).read_bytes() == (self.REFERENCES_DIR / reference).read_bytes(), (
                f"{target_name}: references/{reference} is stale — run `make build`"
            )
