# >>> pipelex-codegen-stamp >>>
# crate_fingerprint: f2d0368168cac603b14d22e5c28923416bc45056eb9b0f4bd7aa69ae60d9ff91
# engine_version: 0.43.1
# projection: types / python-structures
# options: {}
# content_hash: 9a1a8c5af4f8e1ccfcf8708339d4750e9c10a04f6492dfe7f755fb1034a28500
# <<< pipelex-codegen-stamp <<<
# ---------------------------------------------------------------------------
# AUTOGENERATED by Pipelex codegen — DO NOT EDIT.
#
# This file is a projection of a normalized MTHDS library crate. It is
# regenerated from the method; any hand edit here is overwritten.
#
# To customize a generated type, do NOT edit this file. Create a sibling
# module and subclass — subclasses survive regeneration:
#
#     # my_types_ext.py
#     from .structures import Report
#
#     class MyReport(Report):
#         ...
#
# projection: types / python-structures
# ---------------------------------------------------------------------------
from __future__ import annotations

from typing import Literal

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class ActionPlan(StructuredContent):
    """Recommended actions for the support team next week"""

    actions: list[str] = Field(
        ...,
        description="Concrete actions, highest leverage first",
    )
    rationale: str = Field(
        ...,
        description="Why these actions follow from the themes and the breaches",
    )


class CategoryStat(StructuredContent):
    """Aggregated ticket figures for a single category"""

    category: str = Field(..., description="The category these figures cover")
    ticket_count: int = Field(..., description="Tickets closed in this category")
    median_resolution_hours: float = Field(
        ...,
        description="Median hours to resolution in this category",
    )
    mean_satisfaction: float = Field(
        ...,
        description="Mean CSAT across rated tickets in this category",
    )


class SlaBreach(StructuredContent):
    """A ticket that resolved outside the service level allowed for its priority"""

    ticket_id: str = Field(..., description="The breaching ticket")
    category: str = Field(..., description="Product area the ticket concerns")
    priority: str = Field(..., description="Triage priority of the breaching ticket")
    resolution_hours: float = Field(..., description="Hours the ticket actually took")
    allowed_hours: float = Field(..., description="Hours its priority allowed")


class SupportDigest(StructuredContent):
    """The finished weekly digest, ready to paste into a team channel"""

    headline: str = Field(..., description="One-line summary of the week")
    stats_table: str = Field(
        ...,
        description="Markdown table of the per-category figures",
    )
    breach_count: int = Field(..., description="How many tickets breached their SLA")
    narrative: str = Field(
        ...,
        description="The themes narrative, carried through verbatim",
    )
    actions: list[str] = Field(..., description="The recommended actions")


class ThemeSummary(StructuredContent):
    """Recurring themes a reader should notice in the week's tickets"""

    themes: list[str] = Field(
        ...,
        description="Short theme labels, most prominent first",
    )
    narrative: str = Field(
        ...,
        description="A paragraph explaining what the themes have in common",
    )


class TicketRow(StructuredContent):
    """One support ticket from the week under review"""

    ticket_id: str = Field(..., description="Unique ticket identifier")
    category: str = Field(..., description="Product area the ticket concerns")
    priority: Literal["low", "medium", "high", "urgent"] = Field(
        ...,
        description="Triage priority",
    )
    resolution_hours: float = Field(..., description="Hours from open to resolution")
    satisfaction: int = Field(
        ...,
        description="CSAT score from 1 to 5, or 0 when the requester did not rate",
    )


class TicketStats(StructuredContent):
    """Weekly ticket totals with a per-category breakdown"""

    total_tickets: int = Field(..., description="Tickets closed during the week")
    median_resolution_hours: float = Field(
        ...,
        description="Median hours to resolution across all tickets",
    )
    mean_satisfaction: float = Field(
        ...,
        description="Mean CSAT across all rated tickets",
    )
    by_category: list[CategoryStat] = Field(
        ...,
        description="Per-category figures, busiest category first",
    )
